### PR TITLE
Open Symfony 3 compatibility

### LINKED ISSUE #668: Can't install Bundle on Symfony 3
When trying to install SonataPageBundle 3.0.0 on Symfony 3.1.0 you get an error saying that there is a version conflict on the symfony/options-resolver package.

Symfony requires a 3.1.0 version whereas SonataPageBundle asks for a ^2.3

| Question | Answer |
| --- | --- |
| Bundle version | 3.0.0 |
| Symfony version | 3.1.0 |
| php version | 5.6.22 |
# Error message

``` bash
Problem 1
    - Installation request for sonata-project/page-bundle ^3.0 -> satisfiable by sonata-project/page-bundle[3.0.0].
    - Conclusion: remove symfony/symfony v3.1.0
    - sonata-project/page-bundle 3.0.0 requires symfony/options-resolver ^2.3
```
# Steps to reproduce

Create new Symfony Project based on 3.x.
Follow SonataPageBundle docs to install last stable.
Launch `composer update`
# Expected results

SonataPageBundle installs correctly
# Actual results

SonataPageBundle doesn't install and can't be used.

### PR DESCRIPTION
**Pull request by greg0ire**
I am targeting this branch, because this is BC.

Closes #668 

## Changelog

```markdown
### Fixed
- Compatibility with Symfony 3 was fixed
```

## To do

See https://github.com/sonata-project/SonataPageBundle/projects/1

### CODE REVIEW

File: Tests/Form/Type/PageSelectorTypeTest.php [hunk 1]
```diff
@@ -103,106 +108,136 @@ public function testAllRequestMethodChoices()
...
+        );
+        $views = $options['choice_list']->getChoices();
 
         $this->assertCount(3, $views);
-        $this->assertEquals('all', $views[0]->label->getRouteName());
-        $this->assertEquals('get', $views[1]->label->getRouteName());
-        $this->assertEquals('get-post', $views[2]->label->getRouteName());
+        $this->assertEquals('all', $views[0]->getRouteName());
+        $this->assertEquals('get', $views[1]->getRouteName());
+        $this->assertEquals('get-post', $views[2]->getRouteName());
```
Comment (greg0ire) [inline Tests/Form/Type/PageSelectorTypeTest.php]: I think I have to make this conditional to fix some builds.

**Comment by greg0ire** [comment]
Please test @aimeric @Id4v @jmontoyaa @robbert-vdh @pbrzoski @bruno-ds

**Comment by jmontoyaa** [comment]
In composer i have this:

```
...
  "symfony/symfony": "3.*",
  "sonata-project/page-bundle": "~3.0",
...
```

Then I have as result: 

` sonata-project/page-bundle 3.4.1 requires symfony/validator ^2.3 `

**Comment by greg0ire** [comment]
@jmontoyaa this is not merged yet. If you want to test, you have to use an [inline alias](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias)

**Comment by skoubin** [comment]
@jmontoyaa  the PR hasn't been merged yet (if I am not mistaken) so you cannot get it through the official SonataPage repo.

However you can install it temporarily by adding the following to your composer.json file:
```javascript
......
"repositories": [   
        {   
            "url": "https://github.com/greg0ire/SonataPageBundle",   
            "type": "git"   
        }   
    ],
"require":{
     .......
    "sonata-project/page-bundle": "dev-sf3-compat"
}
......   
```
Installing from greg0ire repo worked fine but I got some XSD schema errors at [page.xml](https://github.com/greg0ire/SonataPageBundle/blob/sf3-compat/Resources/config/page.xml).
Attributes **scope**, **factory-method** and **factory-service** are not allowed.

The exact error is shown below:

```[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]             
    Unable to parse file "....../vendor/sonata            
    -project/page-bundle/DependencyInjection/../Resources/config/page.xml".                                                                                                       
                                 
                                                          
    [InvalidArgumentException]                                                             
    [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', att            
    ribute 'scope': The attribute 'scope' is not allowed. (in line 49, column 0)                                           
    [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', att            
    ribute 'scope': The attribute 'scope' is not allowed. (in line 56, column 0)                                           
    [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', att            
    ribute 'factory-method': The attribute 'factory-method' is not allowed. (in line 81, column 0)                         
    [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', att            
    ribute 'factory-service': The attribute 'factory-service' is not allowed. (            
    in line 81, column 0)
``` 
@greg0ire is that a bug or did I install the wrong branch?

**Comment by greg0ire** [comment]
@skoubin thanks for the explanation, you did great and found a new bug! Adding it to the TODO list

**Comment by skoubin** [comment]
@greg0ire Is this PR supposed to get the PageBundle compatible with Symfony 3 completely? I fixed the bug I mentioned earlier but I think I found some more issues along the way. This is the first time I use (or trying to use) the SonataPage bundle and I am not fully familiar with the internal logic..so debugging takes time!

Shall I post those issues under this thread or you prefer another space?

**Comment by greg0ire** [comment]
> @greg0ire Is this PR supposed to get the PageBundle compatible with Symfony 3 completely?

It's a best effort: I'm not using this bundle, so I'm only relying on the test suite to find the BC-breaks. Looks like the coverage is not good enough :/

> I fixed the bug I mentioned earlier but I think I found some more issues along the way.

PRs on my fork are welcome, but the thing is, it has to work for low versions of symfony / php too :P

> Shall I post those issues under this thread or you prefer another space?

I think this thread is the best place. Please do post your findings.

**Comment by greg0ire** [comment]
> Looks like the coverage is not good enough :/

I created #811 to improve this

**Comment by skoubin** [comment]
cool.
So far I have found the followings:
 - **Dialog** helper needs to be replaced with **Question** helper at [CreateSiteCommand](https://github.com/sonata-project/SonataPageBundle/blob/3.x/Command/CreateSiteCommand.php) file.
 - **form.csrf_provider** needs to be replaced with **security.crsd.token_manager** at file [PageAdminController](https://github.com/sonata-project/SonataPageBundle/blob/3.x/Controller/PageAdminController.php#L206)
 -  **generateCsrfToken** needs to be replace with **getToken** method at file [PageAdminController](https://github.com/sonata-project/SonataPageBundle/blob/3.x/Controller/PageAdminController.php#L216)
 - Form types must be reference with FQCN instead of Type names
 - **addViolationAt** needs to be replaced with **buildViolation** method at file [UniqueURLValidation](https://github.com/sonata-project/SonataPageBundle/blob/3.x/Validator/UniqueUrlValidator.php#L74)

Most of the above are explained at [Symfony Upgrade to 3.0 doc](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md)

ps This is what I have found so far but I have the impression that there are more bugs as I haven't managed to make it work yet.

@greg0ire  I will go through the [Contributing doc](https://github.com/sonata-project/SonataPageBundle/blob/3.x/CONTRIBUTING.md) first (as I am not an experienced contributor) and then I will create PRs at your repo

**Comment by greg0ire** [comment]
> @greg0ire I will go through the Contributing doc first (as I am not an experienced contributor) and then I will create PRs at your repo

Awesome

I think most of the PRs can even be created as standalone PRs, just like #812 (it will benefit users that use sf 2 too and can be merged without opening compatibility). It will be easier for you anyway.

File: Tests/Validator/UniqueUrlValidatorTest.php [hunk 2]
```diff
@@ -99,6 +102,7 @@ public function testValidateWithRootUrlAndNoParent()
 
     public function testValidateWithPageDynamic()
     {
+        $this->skipInPHP55();
```
Comment (core23) [inline Tests/Validator/UniqueUrlValidatorTest.php]: Not sure, if this is a good idea. This code would work on PHP 5.5. 

IMHO this is a dependency problem

Comment (greg0ire) [inline Tests/Validator/UniqueUrlValidatorTest.php]: What do you mean by "a dependency problem" ?

Comment (core23) [inline Tests/Validator/UniqueUrlValidatorTest.php]: Can you explain which line wouldn't run under PHP 5.5?

Comment (greg0ire) [inline Tests/Validator/UniqueUrlValidatorTest.php]: No, I'm afraid I don't understand what is happening here. See https://travis-ci.org/sonata-project/SonataPageBundle/jobs/228055349#L463

Comment (core23) [inline Tests/Validator/UniqueUrlValidatorTest.php]: I few months ago, I got the same error. 

It's kind of a PHPUnit bug, when you declare a class alias in the `use` section which already exists as a real class name. E.g. your class `Item` is in the `AppBundle\Entity` namespace and you are importing the class `use FooBundle\Bar\Baz;` But a class `AppBundle\Entity\Baz` exists.

Sadly, I can't find the code which fixes the problem, but i think defining a class alias like `use FooBundle\Bar\Baz as TestBaz;` should fix the problem.

Comment (greg0ire) [inline Tests/Validator/UniqueUrlValidatorTest.php]: Thanks, but this is probably a different quirk, because I'm not importing `ExecutionContextInterface` anywhere.

**Comment by greg0ire** [comment]
Proposed solution for the scope issues : 
- in https://github.com/sonata-project/SonataPageBundle/blob/3.x/Command/RenderBlockCommand.php#L81 , we are faking a `request` service and entering the `request` scope. If the `RequestStack` class exists, fake that instead.
- in https://github.com/sonata-project/SonataPageBundle/blob/3.x/Resources/config/page.xml#L49-L61 , we are scoping some services in the `request` scope. Do that only if the `RequestStack` class does not exist.

**Comment by greg0ire** [comment]
> addViolationAt needs to be replaced with buildViolation method at file UniqueURLValidation

working on that right now

**Comment by OskarStark** [comment]
#814 is merged now 👍

**Comment by Dunduro** [comment]
Hi, i was wondering if there have been any status updates? 
i tried adding the repo as explained about
`"repositories": [   
        {   
            "url": "https://github.com/greg0ire/SonataPageBundle",   
            "type": "git"   
        }   
    ],
"require":{
     .......
    "sonata-project/page-bundle": "dev-sf3-compat"
}`

but symfony kept complaining about the scope being an unauthorized attribute. am i doing something wrong or adding the wrong repo?

**Comment by greg0ire** [comment]
I need to rebase this

**Comment by greg0ire** [comment]
If you want to help, see https://github.com/sonata-project/SonataPageBundle/projects/1

**Comment by greg0ire** [comment]
@Dunduro I rebased, you should no longer have the warning about scopes if you update.

**Comment by greg0ire** [comment]
@Dunduro fixed all the remaining issues I think. I rebased, can any of you test again, see if there are more issues that needs to be addressed?

File: Tests/Validator/UniqueUrlValidatorTest.php (hunk 2 above)
Comment (core23) [inline Tests/Validator/UniqueUrlValidatorTest.php]: PHP 5.5 is EOL, so it's okay for me

**Comment by greg0ire** [comment]
ping @aimeric @Id4v @jmontoyaa @robbert-vdh @pbrzoski @bruno-ds

**Comment by greg0ire** [comment]
If no one wants to test, can you please just merge this @sonata-project/contributors ?

**Comment by OskarStark** [comment]
Thank you @greg0ire 🎉
