### PR TITLE
Stop calling static method in a non-static way

### LINKED ISSUE #760: The 3.x build is broken
See https://github.com/sonata-project/SonataPageBundle/pull/758#issuecomment-269797358

It fails on [this particular line](https://github.com/sonata-project/SonataPageBundle/blob/3.x/Twig/Extension/PageExtension.php#L289), with the following message : `PHPUnit_Framework_MockObject_BadMethodCallException`, only with php 5.5

### PR DESCRIPTION
**Pull request by greg0ire**
I am targetting this branch, because this is BC.

## Subject

Fixes the broken test suite

Closes #760

Since symfony/twig-bridge#3.2, HttpKernelExtension::controller is no
longer static. This is not a problem when running the code, but it is
when trying to mock the extension and then call the method on it. This
fix calls the extension method statically and removes the mocking calls
when appropriate.

To be merged asap 🚨

### CODE REVIEW

**Comment by greg0ire** [comment]
Aaaaaaaargh! The method wasn't always static! Shit…

**Comment by greg0ire** [comment]
Found another solution.

**Comment by greg0ire** [comment]
Merging since this is a blocker.

File: Tests/Twig/Extension/PageExtensionTest.php [hunk 1]
```diff
@@ -66,12 +66,14 @@ public function testController()
...
         $extension = new PageExtension($cmsManager, $siteSelector, $router, $blockHelper, $HttpKernelExtension);
         $extension->initRuntime($env);
-        $HttpKernelExtension->expects($this->once())->method('controller')->with(
-            'foo',
-            array('pathInfo' => '/foo/bar/'),
-            array()
-        )
-        ;
+        if (!method_exists('Symfony\Bridge\Twig\AppVariable', 'getToken')) {
+            $HttpKernelExtension->expects($this->once())->method('controller')->with(
```
Comment (OskarStark) [inline Tests/Twig/Extension/PageExtensionTest.php]: @greg0ire can you rename the variable to `$httpKernelExtension` (starting lowercase instead of uppercase) ?

File: Tests/Twig/Extension/PageExtensionTest.php [hunk 2]
```diff
@@ -66,12 +66,14 @@ public function testController()
...
+                'foo',
+                array('pathInfo' => '/foo/bar/'),
+                array()
+            )
+            ;
```
Comment (OskarStark) [inline Tests/Twig/Extension/PageExtensionTest.php]: this looks weird

Comment (greg0ire) [inline Tests/Twig/Extension/PageExtensionTest.php]: Yes, but I didn't do it.

File: Tests/Twig/Extension/PageExtensionTest.php (hunk 1 above)
Comment (greg0ire) [inline Tests/Twig/Extension/PageExtensionTest.php]: This is already merged @OskarStark :P

Comment (greg0ire) [inline Tests/Twig/Extension/PageExtensionTest.php]: Also, I didn't do that either… I wanted the diff to be as small as possible b/c this was critical and needed to be merged with no discussions about style

Comment (greg0ire) [inline Tests/Twig/Extension/PageExtensionTest.php]: You can see the "real" diff here : https://github.com/sonata-project/SonataPageBundle/pull/761/files?w=0 (I added `?w=0`)

Comment (OskarStark) [inline Tests/Twig/Extension/PageExtensionTest.php]: I know, that this was not your fault, but i thought you could fix it quickly in a separate PR ;-)

Comment (greg0ire) [inline Tests/Twig/Extension/PageExtensionTest.php]: Ok, I will.
