### PR TITLE
use choices instead of choices_list in PageSelectorType. Fixes #823

### LINKED ISSUE #823: Updating to 3.5.0 breaks new page creation
#### composer.json
symfony 2.8 with
https://github.com/EntropyRy/Tunkki/blob/5e9fb61deb1a21a4de96f9bc8de17617383131e3/symfony/composer.json

#### PHP version

```bash
$ php -v
PHP 7.1.5 (cli) (built: May 13 2017 00:27:38) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.5, Copyright (c) 1999-2017, by Zend Technologies
```

## Steps to reproduce

1. Create new page
2. try to select parent page
3. update

## Expected results

parent page is valid and page is updated

## Actual results
parent page is not listed by names. It is listed by id's and after update is says
"The root URL '/' is already associated with another page of this site, please select a parent."

## quick fix

downgrade to pagebundle 3.4. compsoer says:
```
Package operations: 0 installs, 3 updates, 0 removals
  - Updating symfony-cmf/routing (2.0.1 => 1.4.1): Downloading (100%)         
  - Updating symfony-cmf/routing-bundle (2.0.0 => 1.4.0): Downloading (100%)         
  - Updating sonata-project/page-bundle (3.5.0 => 3.4.0): Downloading (100%) 
```
now everything is working again

### PR DESCRIPTION
**Pull request by n3o77**
I am targeting this branch, because 3.5 introduced the problem.

Fixes #823 

Closes #823 

## Changelog

use choices instead of choices_list in PageSelectorType

```markdown
### Fixed
- parent page select input no longer has flipped choices

```

## To do

- [x] Run tests to assure backwards compatibility

### CODE REVIEW

File: Form/Type/PageSelectorType.php [hunk 1]
```diff
@@ -51,10 +51,8 @@ public function configureOptions(OptionsResolver $resolver)
         $resolver->setDefaults(array(
             'page' => null,
             'site' => null,
-            'choice_list' => function (Options $opts, $previousValue) use ($that) {
-                return class_exists('Symfony\Component\Form\ChoiceList\ArrayChoiceList') ?
-                    new ArrayChoiceList($that->getChoices($opts)) :
-                    new SimpleChoiceList($that->getChoices($opts)); // NEXT_MAJOR: remove condition
+            'choices' => function (Options $opts, $previousValue) use ($that) {
+                return $that->getChoices($opts);
```
Comment (greg0ire) [inline Form/Type/PageSelectorType.php]: `choices` has been around since the beginning IIRC, so this could be BC.

**Comment by greg0ire** [comment]
I edited the changelog

**Comment by greg0ire** [comment]
You could squash these two commits together ;)

**Comment by n3o77** [comment]
I guess i have to adjust some tests.

**Comment by n3o77** [comment]
@greg0ire Tests seem to be good now. I'd appreciate if you could review them if they still make sense. I had to change the array keys as they're the page ids.

**Comment by greg0ire** [comment]
> I'd appreciate if you could review them if they still make sense.

I think you did just fine. They did not make a lot of sense in the first place but it is good that this piece of code gets covered, because of deprecations messages it provides us with.

**Comment by greg0ire** [comment]
@sonata-project/contributors please review

**Comment by haivala** [comment]
I think this merge should be released as 3.5.1 ?

**Comment by greg0ire** [comment]
I'll ask for a release.

**Comment by OskarStark** [comment]
Released here in tag [3.5.1](https://github.com/sonata-project/SonataPageBundle/releases/tag/3.5.1)
