### PR TITLE
fix Cleanup Query if no snapshot to keep

### LINKED ISSUE #1535: Cleanup Query fails if there is no Snapshot to keep
I executed the `bin/console sonata:page:cleanup-snapshots` and I got this error

```
In QueryException.php line 32:
                                                                   
  [Syntax Error] line 0, col 74: Error: Expected Literal, got ')'  
                                                                   

In QueryException.php line 21:
                                                                               
  DELETE App\Entity\SonataPageSnapshot s WHERE s.page = 653 AND s.id NOT IN()  
```

any idea @Hanmac ?

_Originally posted by @eerison in https://github.com/sonata-project/SonataPageBundle/issues/1495#issuecomment-1210281812_

### PR DESCRIPTION
**Pull request by Hanmac**
## Subject

The Query is faulty if there is no Snapshot to keep.
I should probably extend the Testcases for this too.

I am targeting this branch, because it is a Bug Fix.

Closes #1535.

## Changelog

```markdown
### Fixed
- SnapshotManager Cleanup Query if there are no Snapshots to keep
```

### CODE REVIEW

File: src/Entity/SnapshotManager.php [hunk 1]
```diff
@@ -256,11 +256,14 @@ public function cleanup(PageInterface $page, $keep)
         $qb = $this->getRepository()->createQueryBuilder('s');
         $expr = $qb->expr();
         $qb->delete()
-            ->where($expr->eq('s.page', $page->getId()))
-            ->andWhere($expr->notIn(
+            ->where($expr->eq('s.page', $page->getId()));
+
+        if (!empty($innerArray)) {
```
Comment (VincentLanglet) [inline src/Entity/SnapshotManager.php]: Please do not use empty. Prefer a `[] !==` check or a count check

**Review by VincentLanglet — CHANGES_REQUESTED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]
