### PR TITLE
Fixed FQCN issue reported in issue #830

### LINKED ISSUE #830: Additional symfony 3 admin bundle intergration issues FQCN
#### Sonata packages

sonata-project/admin-bundle              3.20.0          The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2           Symfony SonataBlockBundle
sonata-project/cache                     1.0.7           Cache library
sonata-project/cache-bundle              2.3.1           This bundle provides caching services
sonata-project/core-bundle               3.4.0           Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1           Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2           Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.5           Symfony Sonata / Integrate Doctrine ORM into the Sonata...
sonata-project/easy-extends-bundle       2.2.0           Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1           Lightweight Exporter library
sonata-project/notification-bundle       3.1.0           Symfony SonataNotificationBundle
sonata-project/page-bundle               3.x-dev c08500f This bundle provides a Site and Page management through...
sonata-project/seo-bundle                2.2.0           Symfony SonataSeoBundle

#### Symfony packages

symfony/assetic-bundle     v2.8.1 Integrates Assetic into Symfony2
symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.2 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.4.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.4.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.4.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.4.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.4.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.4.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2 Symfony SwiftmailerBundle
symfony/symfony            v3.2.9 The Symfony PHP framework

#### PHP version

PHP 5.6.30 (cli) (built: Jan 18 2017 19:48:14)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans

## Subject

As noted in issue #820, admin classes are still using string based form types.
Form types must be declared as FullQualifiedClassName.

## Steps to reproduce

Visit the /admin/sonata/page/page/2/edit edit page.

## Expected results

Form to edit the page.

## Actual results

```
Could not load type "sonata_page_type_choice"
500 Internal Server Error - InvalidArgumentException
```
Stacktrace
```
[1] Symfony\Component\Form\Exception\InvalidArgumentException: Could not load type "sonata_page_type_choice"
    at n/a
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\vendor\symfony\symfony\src\Symfony\Component\Form\FormRegistry.php line 87

    at Symfony\Component\Form\FormRegistry->getType('sonata_page_type_choice')
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\vendor\symfony\symfony\src\Symfony\Component\Form\FormFactory.php line 83

    at Symfony\Component\Form\FormFactory->createNamedBuilder('type', 'sonata_page_type_choice', null, array('sonata_field_description' => object(FieldDescription), 'required' => false, 'property_path' => 'type', 'label_render' => false, 'label' => 'form.label_type'))
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\vendor\symfony\symfony\src\Symfony\Component\Form\FormBuilder.php line 106

    at Symfony\Component\Form\FormBuilder->create('type', 'sonata_page_type_choice', array('sonata_field_description' => object(FieldDescription), 'required' => false, 'property_path' => 'type', 'label_render' => false, 'label' => 'form.label_type'))
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\vendor\symfony\symfony\src\Symfony\Component\Form\FormBuilder.php line 269

    at Symfony\Component\Form\FormBuilder->resolveChildren()
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\vendor\symfony\symfony\src\Symfony\Component\Form\FormBuilder.php line 215

    at Symfony\Component\Form\FormBuilder->getForm()
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\var\cache\dev\classes.php line 13308

    at Sonata\AdminBundle\Admin\AbstractAdmin->buildForm()
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\var\cache\dev\classes.php line 12342

    at Sonata\AdminBundle\Admin\AbstractAdmin->getForm()
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\vendor\sonata-project\admin-bundle\Controller\CRUDController.php line 255

    at Sonata\AdminBundle\Controller\CRUDController->editAction('2')
        in  line 

    at call_user_func_array(array(object(PageAdminController), 'editAction'), array('2'))
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\var\cache\dev\classes.php line 4228

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\var\cache\dev\classes.php line 4183

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php line 168

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\web\app_dev.php line 28

    at require('C:\\Users\\dmeigs.TLINENM\\Documents\\websites\\AYSOUnited\\web\\app_dev.php')
        in C:\Users\dmeigs.TLINENM\Documents\websites\AYSOUnited\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Resources\config\router_dev.php line 40

500 @ admin_sonata_page_page_edit
2418 ms
50.8 MB
 1
```

This error is given by line 356
```
->add('type', 'sonata_page_type_choice', array('required' => false))
```

The same problem exists on line 363 with 'sonata_page_template', line 370 with 'sonata_page_selector', and line 391 with 'sonata_page_selector'.

All need a FQCN that doesn't break bc.

### PR DESCRIPTION
**Pull request by dmeigs**
I am targeting this branch, because of the bug noted in issue #830.

In case of bug fix, `3.x` **MUST** be targeted.

Closes #830

## Changelog

```markdown
### Fixed
- form typess are referenced by FQCN and not by name, which is no longer supported
```

## Subject

This pull request corrects the issues noted in issue #830 following the pattern used in issue #820. This will need testing to ensure backward compatibility.

### CODE REVIEW

File: Admin/PageAdmin.php [hunk 1]
```diff
@@ -353,33 +353,45 @@ protected function configureFormFields(FormMapper $formMapper)
         if ($this->hasSubject() && !$this->getSubject()->isInternal()) {
             $formMapper
                 ->with('form_page.group_main_label')
-                    ->add('type', 'sonata_page_type_choice', array('required' => false))
+//                    ->add('type', 'sonata_page_type_choice', array('required' => false))
```
Comment (greg0ire) [inline Admin/PageAdmin.php]: Don't comment, remove, git is here if you need the old code back.

File: Admin/PageAdmin.php [hunk 2]
```diff
@@ -353,33 +353,45 @@ protected function configureFormFields(FormMapper $formMapper)
...
-                        'admin_code' => $this->getCode(),
-                        'link_parameters' => array(
-                            'siteId' => $this->getSubject() ? $this->getSubject()->getSite()->getId() : null,
-                        ),
-                    ))
+//                    ->add('parent', 'sonata_page_selector', array(
+                    ->add('parent', method_exists('Symfony\Component\Form\AbstractType', 'getBlockPrefix') ?
+                        'Sonata\PageBundle\Form\Type\PageSelectorType' :
+                        'sonata_page_selector',
+                        array(
```
Comment (greg0ire) [inline Admin/PageAdmin.php]: This violates PSR2, and is why the diff looks so big : either put all the arguments of `add` on the same "line", or put one argument per line, but not both, please.

**Comment by greg0ire** [comment]
I edited your changelog and removed the todo list: there is no need to update the documentation, as for the tests, please check if this is covered or not.

File: Admin/PageAdmin.php [hunk 3]
```diff
@@ -353,33 +353,48 @@ protected function configureFormFields(FormMapper $formMapper)
...
+                        array('required' => false))
                 ->end()
             ;
         }
 
         $formMapper
             ->with('form_page.group_main_label')
-                ->add('templateCode', 'sonata_page_template', array('required' => true))
+//                ->add('templateCode', 'sonata_page_template', array('required' => true))
+                ->add('templateCode',
```
Comment (greg0ire) [inline Admin/PageAdmin.php]: 'templateCode' needs to be on its own line too if you want to conform with PSR2

**Comment by greg0ire** [comment]
@dmeigs can you remove the lines you commented out please?

**Comment by greg0ire** [comment]
Oh sorry I understand what the commented code was about now: it's not old code, it's future code! Can you please `reset --hard 093aa0f` and then `push --force`, if that's indeed what it was?

**Comment by dmeigs** [comment]
@greg0ire You were right the first time: that was old code. I commented out the code I replaced. It's better off gone!

**Comment by greg0ire** [comment]
Oh right, I think I was confused.

**Comment by dmeigs** [comment]
@greg0ire I see the confusion. In my haste, I deleted a future code segment offered in the PR associated with #820. I've updated the PR.

File: Admin/PageAdmin.php [hunk 4]
```diff
@@ -353,33 +353,48 @@ protected function configureFormFields(FormMapper $formMapper)
         if ($this->hasSubject() && !$this->getSubject()->isInternal()) {
             $formMapper
                 ->with('form_page.group_main_label')
-                    ->add('type', 'sonata_page_type_choice', array('required' => false))
+                    ->add(
+                        'type',
+                        method_exists('Symfony\Component\Form\AbstractType', 'getBlockPrefix') ?
```
Comment (OskarStark) [inline Admin/PageAdmin.php]: we should add a next_major here

Comment (greg0ire) [inline Admin/PageAdmin.php]: @dmeigs this is where "future code" should kick in. Be sure to include a `NEXT_MAJOR` comment so that we know what it is about.

Comment (Soullivaneuh) [inline Admin/PageAdmin.php]: Same for the other parts BTW.

Comment (dmeigs) [inline Admin/PageAdmin.php]: @OskarStark this has been done. Please review.

File: Admin/PageAdmin.php [hunk 5]
```diff
@@ -290,7 +290,10 @@ protected function configureDatagridFilters(DatagridMapper $datagridMapper)
                     'Sonata\PageBundle\Form\Type\PageTypeChoiceType' :
                     'sonata_page_type_choice',
             ))
-//            ->add('type', null, array('field_type' => 'Sonata\PageBundle\Form\Type\PageTypeChoiceType'))
+/*
+ * NEXT_MAJOR
+ *          ->add('type', null, array('field_type' => 'Sonata\PageBundle\Form\Type\PageTypeChoiceType'))
+ */
```
Comment (greg0ire) [inline Admin/PageAdmin.php]: I was gonna ask why this is not indented but it looks like it was like this in the first place...

**Comment by greg0ire** [comment]
@sonata-project/contributors  please review again

File: Admin/PageAdmin.php [hunk 6]
```diff
@@ -351,56 +351,92 @@ protected function configureFormFields(FormMapper $formMapper)
...
             $formMapper
                 ->with('form_page.group_main_label')
-                    ->add('type', 'sonata_page_type_choice', array('required' => false))
+                    ->add(
+                        'type',
+                        method_exists('Symfony\Component\Form\AbstractType', 'getBlockPrefix') ?
+                            'Sonata\PageBundle\Form\Type\PageTypeChoiceType' :
+                            'sonata_page_type_choice',
+//                        'Sonata\PageBundle\Form\Type\PageTypeChoiceType',
+                        array('required' => false))
```
Comment (Soullivaneuh) [inline Admin/PageAdmin.php]: The last `)` should be on new line.

File: Admin/PageAdmin.php [hunk 7]
```diff
@@ -351,56 +351,92 @@ protected function configureFormFields(FormMapper $formMapper)
...
+             */
             $formMapper
                 ->with('form_page.group_main_label')
-                    ->add('type', 'sonata_page_type_choice', array('required' => false))
+                    ->add(
+                        'type',
+                        method_exists('Symfony\Component\Form\AbstractType', 'getBlockPrefix') ?
+                            'Sonata\PageBundle\Form\Type\PageTypeChoiceType' :
+                            'sonata_page_type_choice',
+//                        'Sonata\PageBundle\Form\Type\PageTypeChoiceType',
```
Comment (Soullivaneuh) [inline Admin/PageAdmin.php]: Commented code.

File: Admin/PageAdmin.php [hunk 8]
```diff
@@ -351,56 +351,92 @@ protected function configureFormFields(FormMapper $formMapper)
...
+         */
         $formMapper
             ->with('form_page.group_main_label')
-                ->add('templateCode', 'sonata_page_template', array('required' => true))
+                ->add(
+                    'templateCode',
+                    method_exists('Symfony\Component\Form\AbstractType', 'getBlockPrefix') ?
+                        'Sonata\PageBundle\Form\Type\TemplateChoiceType' :
+                        'sonata_page_template',
+//                    'Sonata\PageBundle\Form\Type\TemplateChoiceType',
```
Comment (Soullivaneuh) [inline Admin/PageAdmin.php]: Commented code.

File: Admin/PageAdmin.php [hunk 9]
```diff
@@ -351,56 +351,92 @@ protected function configureFormFields(FormMapper $formMapper)
...
+                    array('required' => true))
```
Comment (Soullivaneuh) [inline Admin/PageAdmin.php]: The last `)` should be on new line.

File: Admin/PageAdmin.php [hunk 10]
```diff
@@ -351,56 +351,92 @@ protected function configureFormFields(FormMapper $formMapper)
...
-                        'link_parameters' => array(
-                            'siteId' => $this->getSubject() ? $this->getSubject()->getSite()->getId() : null,
-                        ),
-                    ))
+                    ->add(
+                        'parent',
+                        method_exists('Symfony\Component\Form\AbstractType', 'getBlockPrefix') ?
+                            'Sonata\PageBundle\Form\Type\PageSelectorType' :
+                            'sonata_page_selector',
+//                        'Sonata\PageBundle\Form\Type\PageSelectorType',
```
Comment (Soullivaneuh) [inline Admin/PageAdmin.php]: Commented code.

File: Admin/PageAdmin.php [hunk 11]
```diff
@@ -351,56 +351,92 @@ protected function configureFormFields(FormMapper $formMapper)
...
+                            'model_manager' => $this->getModelManager(),
+                            'class' => $this->getClass(),
+                            'required' => false,
+                            'filter_choice' => array('hierarchy' => 'root'),
+                        ), array(
+                            'admin_code' => $this->getCode(),
+                            'link_parameters' => array(
+                                'siteId' => $this->getSubject() ? $this->getSubject()->getSite()->getId() : null,
+                            ),
+                        ))
```
Comment (Soullivaneuh) [inline Admin/PageAdmin.php]: The last `)` should be on new line.

File: Admin/PageAdmin.php [hunk 12]
```diff
@@ -351,56 +351,92 @@ protected function configureFormFields(FormMapper $formMapper)
...
-                        'link_parameters' => array(
-                            'siteId' => $this->getSubject() ? $this->getSubject()->getSite()->getId() : null,
-                        ),
-                    ))
+                    ->add(
+                        'parent',
+                        method_exists('Symfony\Component\Form\AbstractType', 'getBlockPrefix') ?
+                            'Sonata\PageBundle\Form\Type\PageSelectorType' :
+                            'sonata_page_selector',
+//                        'Sonata\PageBundle\Form\Type\PageSelectorType',
```
Comment (Soullivaneuh) [inline Admin/PageAdmin.php]: Commented code.

File: Admin/PageAdmin.php [hunk 13]
```diff
@@ -351,56 +351,92 @@ protected function configureFormFields(FormMapper $formMapper)
...
+                            'model_manager' => $this->getModelManager(),
+                            'class' => $this->getClass(),
+                            'filter_choice' => array('request_method' => 'all'),
+                            'required' => false,
+                        ), array(
+                            'admin_code' => $this->getCode(),
+                            'link_parameters' => array(
+                                'siteId' => $this->getSubject() ? $this->getSubject()->getSite()->getId() : null,
+                            ),
+                        ))
```
Comment (Soullivaneuh) [inline Admin/PageAdmin.php]: The last `)` should be on new line.

File: Admin/PageAdmin.php (hunk 8 above)
Comment (greg0ire) [inline Admin/PageAdmin.php]: Should come with a NEXT_MAJOR comment

**Comment by dmeigs** [comment]
@Soullivaneuh I fixed the ) on new line comment. 

The commented code goes with the NEXT_MAJOR comments. I followed the pattern for issue #820. If it's wrong, you need to tell me what you want me to do. Is there a guide that says how to comment backward compatibility that needs to be removed in the future?

File: Admin/PageAdmin.php (hunk 8 above)
Comment (dmeigs) [inline Admin/PageAdmin.php]: There's a NEXT_MAJOR comment a couple of lines above that explains this. That's the pattern used on Issue #820. If this is wrong, give me a good example to follow.

Comment (greg0ire) [inline Admin/PageAdmin.php]: Here is how we usually do it: https://github.com/sonata-project/SonataAdminBundle/blob/44d5ec633c51bcbca70ef55862489f3f48bdb850/Mapper/BaseGroupedMapper.php#L74 (we use one `NEXT_MAJOR` per comment. Boring, I know, but less error prone.

**Comment by dmeigs** [comment]
Pardon the ignorance, but how does the Needs: Tests tag get resolved?

**Comment by Soullivaneuh** [comment]
@dmeigs By adding tests to prove the issue and the fix. :wink:

**Comment by greg0ire** [comment]
@Soullivaneuh in this case, I think a unit test would be:

- hard to write
- hard to get anything but coverage out of

Plus to detect deprecations, there would be a need for something in the phpunit-bridge that wasn't released yet last time I checked.

**Comment by Soullivaneuh** [comment]
Having a test which just instantiate a `PageAdmin` and call the modified method just to see if it's working without error would be a good start IMO.

**Comment by greg0ire** [comment]
There already is a `PageAdminTest` class, so at least @dmeigs wouldn't be starting from zero. Can you give it a try and report back @dmeigs ? I think you wouldn't be able to detect deprecation, but just writing a smoke test that shows that the method does not crash would indeed be something.

**Comment by dmeigs** [comment]
@greg0ire Writing a unit test for the protected method configureFormFields requires that I instantiate a FormMapper in my test code. I can't figure out how to do that.  Instantiating a FormMapper requires a FormContractor, which evidently, requires an implementation of FormContractorInterface. I just can't figure out how to do it. Any help would be appreciated.

**Comment by greg0ire** [comment]
@dmeigs you should mock dependencies such as this one.

Here is a link showing how to do that with prophecy: https://thephp.cc/news/2015/02/phpunit-4-5-and-prophecy.

Also, the other test in `PageAdminTest` already does that, you should check it out.

**Comment by greg0ire** [comment]
I'm on #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) if you need more help.

**Comment by greg0ire** [comment]
@Soullivaneuh I removed the "Needs: tests" label because: 

1. "don't mock what you don't own" is a rule we should really follow because not following it bit us in the past (page should not know about what internal calls are made in the FormMapper), and if we mock, we get no deprecation, so mocking is really out of question
2. not mocking means building a huge tree of objects before being even able to test
3. this method is not meant to be unit tested, but end-to-end tested, see http://elnur.pro/testing-repositories/
4. we don't have integration test, and can't reasonably expect @dmeigs to set them up.

**Comment by greg0ire** [comment]
@OskarStark @Soullivaneuh please review again

**Comment by Soullivaneuh** [comment]
As you want, but I don't agree with that. We can test any class even just to see if it works as is.

> Not mocking means building a huge tree of objects before being even able to test, and picking a FormContractInterface instance.

In this case, maybe the code structure should be reviewed.

This can be done later, but this is not impossible IMHO.

**Comment by greg0ire** [comment]
@Soullivaneuh it's definitely not impossible of course, but it will surely be a huge pain to setup.

**Comment by greg0ire** [comment]
After discussion with @Soullivaneuh , restoring the label, but merging.

**Comment by greg0ire** [comment]
Thanks @dmeigs !

**Comment by OskarStark** [comment]
Released here in tag [3.5.1](https://github.com/sonata-project/SonataPageBundle/releases/tag/3.5.1)
