### PR TITLE
Overwrite PageAdmin

### LINKED ISSUE #1639: [Doc][Bug] It's throwing an exception when we are decorating PageAdmin
in version 4.x was removed those parameters

https://github.com/sonata-project/SonataPageBundle/blob/3.x/src/Resources/config/admin.xml#L7-L25

I didn't test it yet, But I suspect the only way to overwrite the classes like `PageAdmin` is decorating right?

I don't know! I'll do some tests and add some doc/UPGRADE notes for this!

### PR DESCRIPTION
**Pull request by eerison**
## Subject

I am targeting this branch, because {reason}.

Closes #1639.

### CODE REVIEW

File: src/Controller/PageAdminController.php [hunk 1]
```diff
@@ -119,7 +119,7 @@ public function treeAction(Request $request): Response
         $theme = $this->admin->getFilterTheme();
         $this->setFormTheme($formView, $theme);
 
-        return $this->renderWithExtraParams($this->admin->getTemplateRegistry()->getTemplate('tree'), [
+        return $this->renderWithExtraParams('@SonataPage/PageAdmin/tree.html.twig', [
```
Comment (VincentLanglet) [inline src/Controller/PageAdminController.php]: Kinda weird. Doing this won't allow people to override the template by using the template registry.

Comment (eerison) [reply src/Controller/PageAdminController.php]: hmmmm But can't you overwrite like this

`templates/bundles/SonataPage/PageAdmin/tree.html.twig` ?

Comment (VincentLanglet) [reply src/Controller/PageAdminController.php]: What if you want to override the template for only one admin ?
See https://github.com/sonata-project/SonataPageBundle/issues/1639#issuecomment-1300000091, there is something to look at in the configuration, about decorated services.

Comment (jordisala1991) [reply src/Controller/PageAdminController.php]: I don't see the benefit of this change. Even with the old line of code, if you overwrite the template adding a new one with the same name on the `bundles/SonataPage/PageAdmin` it should work.

Comment (eerison) [reply src/Controller/PageAdminController.php]: Hey @jordisala1991, it was just a try to fix the page admin when I'm decorating the PageAdmin service!

it's the exception: https://github.com/sonata-project/SonataPageBundle/issues/1639#issuecomment-1299912766

**Comment by eerison** [comment]
@VincentLanglet  just to make sure

for now the only way to customize the admin like `PageAdmin` is decorate them, is that correct?

**Comment by VincentLanglet** [comment]
> @VincentLanglet just to make sure
> 
> for now the only way to customize the admin like `PageAdmin` is decorate them, is that correct?

- You can use adminExtensions which should provide all you need.
- You may be able to decorate indeed.

I dunno if we should provide a BasePageAdmin like the BaseMediaAdmin in
https://github.com/sonata-project/SonataMediaBundle/tree/4.x/src/Admin or the Model/UserAdmin in https://github.com/sonata-project/SonataUserBundle/blob/5.x/src/Admin/Model/UserAdmin.php

**Comment by eerison** [comment]
> > @VincentLanglet just to make sure
> > for now the only way to customize the admin like `PageAdmin` is decorate them, is that correct?
> 
> * You can use adminExtensions which should provide all you need.
> * You may be able to decorate indeed.
> 
> I dunno if we should provide a BasePageAdmin like the BaseMediaAdmin in https://github.com/sonata-project/SonataMediaBundle/tree/4.x/src/Admin or the Model/UserAdmin in https://github.com/sonata-project/SonataUserBundle/blob/5.x/src/Admin/Model/UserAdmin.php

> You can use adminExtensions which should provide all you need.

Do you have some example?

> I dunno if we should provide a BasePageAdmin like the BaseMediaAdmin

IMO it's not really interesting because it's almost the same to have PageAdmin without `final` and if I do this, I need to do the same thing for all admins in this bundle because I need to customiza almost all of them :D

**Comment by VincentLanglet** [comment]
>> You can use adminExtensions which should provide all you need.
>
> Do you have some example?

https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/extensions/
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Admin/Extension/LockExtension.php
https://github.com/sonata-project/SonataMediaBundle/pull/2348

File: docs/reference/customize_admin.rst [hunk 2]
```diff
@@ -0,0 +1,65 @@
+Customize admin
+================
+
+Sonata page bundle there are few admins that can be customize using `Admin Extension`_
+As example if you want to add a new field in ``configureListFields``, You can do like this
+
+.. code-block:: php
```
Comment (eerison) [inline docs/reference/customize_admin.rst]: Hey @VincentLanglet  any ida why lint is complaining about this line?

it's the same of : https://raw.githubusercontent.com/sonata-project/SonataAdminBundle/4.x/docs/reference/form_types.rst

Comment (VincentLanglet) [reply docs/reference/customize_admin.rst]: Dont know a lot about this linter, but the message seems explicit.

File: docs/reference/customize_admin.rst [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+
+    namespace App\Admin\Extension;
+
+    use Sonata\AdminBundle\Admin\AbstractAdminExtension;
+    use Sonata\AdminBundle\Datagrid\ListMapper;
+    use Symfony\Component\DependencyInjection\Attribute\AutoconfigureTag;
+
+    #[AutoconfigureTag(name: 'sonata.admin.extension', attributes: ['target' => 'sonata.page.admin.page'])]
+    final class PageAdminExtension extends AbstractAdminExtension
```
Comment (VincentLanglet) [inline docs/reference/customize_admin.rst]: Isn't this doc enough https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/extensions/ ?

File: docs/reference/customize_admin.rst (hunk 2 above)
Comment (eerison) [reply docs/reference/customize_admin.rst]: I don't know why, But it works with `::`!

File: docs/reference/customize_admin.rst [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+        {
+            $list->add('id');
+        }
+    }
+
+And you will see the field in the end of the table
+
+.. image:: ../images/customize_admin__add_id.png
+
+And for order the field to the begin of your table can use the method ``reorder``
```
Comment (VincentLanglet) [inline docs/reference/customize_admin.rst]: There is no occurence of `reorder` in the SonataAdmin doc
https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/search/?q=reorder&check_keywords=yes&area=default

I think it would be better to document this in this doc.

Not sure it's better in the list section https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/action_list/#
 in the Extension section  https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/extensions/
or in both

**Comment by eerison** [comment]
ScreenShot Tool -20221107135702

File: docs/reference/customize_admin.rst (hunk 4 above)
Comment (eerison) [reply docs/reference/customize_admin.rst]: I guess it will be used more for ExtensionAdmin!

Comment (VincentLanglet) [reply docs/reference/customize_admin.rst]: I think too (for the record it works for also others methods, like configureshowFields for instance)

Comment (VincentLanglet) [reply docs/reference/customize_admin.rst]: I think it would be better to
- Improve SonataAdmin doc first
- Eventually add a doc like yours in SonataPage with link to SonataAdmin then :)

Comment (eerison) [reply docs/reference/customize_admin.rst]: Ok I'll Open a PR to Admin bundle :)

**Review by VincentLanglet — COMMENTED** [review]
This seems a little "short". I dunno if we need this doc like this...

Maybe we should present the doc in another way.
Instead of a `customize admin` titles, it should be `admin services`, with some text:
"There are some already implemented admin (...):"

Admin name - service name - purpose of the admin

And then a paragraph: "If you need to customize the admin, we recommend you to use admin extension"

File: src/Resources/config/admin.php [hunk 5]
```diff
@@ -126,14 +126,22 @@
...
+        ->set(CreateSnapshotAdminExtension::class)
             ->tag('sonata.admin.extension', ['target' => 'sonata.page.admin.page'])
             ->tag('sonata.admin.extension', ['target' => 'sonata.page.admin.block'])
             ->args([
                 new ReferenceConfigurator('sonata.page.service.create_snapshot'),
             ])
 
+        ->alias(PageAdmin::class, 'sonata.page.admin.page')
+
         ->alias(BlockAdmin::class, 'sonata.page.admin.block')
```
Comment (eerison) [inline src/Resources/config/admin.php]: Hey @VincentLanglet 

is it fine we use the `class` as a service and `the string` as an alias like this?

**Comment by eerison** [comment]
Screenshot 2022-11-18 at 10 40 16

File: src/Resources/config/admin.php (hunk 5 above)
Comment (VincentLanglet) [reply src/Resources/config/admin.php]: This is not done this way for other bundles https://github.com/sonata-project/SonataMediaBundle/blob/4.x/src/Resources/config/doctrine_orm_admin.php

And as far I remember there is a reason. I think this is not recommended for libraries.
So I would let this like it was before.
Maybe @jordisala1991 knows more about it.

**Comment by eerison** [comment]
Ok, I'm using the service name as before ;) 

Screenshot 2022-11-18 at 11 02 12

Note: Sorry for the description I'm without creativity, we can improve this later, what do you think?

**Review by VincentLanglet — COMMENTED** [review]
I'm looking at the phpstan failure.
Already opened https://github.com/doctrine/persistence/pull/315

**Comment by eerison** [comment]
> I'm looking at the phpstan failure. Already opened [doctrine/persistence#315](https://github.com/doctrine/persistence/pull/315)

@VincentLanglet I bumped to ^3.1 :)

**Comment by VincentLanglet** [comment]
> > I'm looking at the phpstan failure. Already opened [doctrine/persistence#315](https://github.com/doctrine/persistence/pull/315)
> 
> @VincentLanglet I bumped to ^3.1 :)

This is not needed, phpstan run on the latest version.
We can still support 3.0.

Revert the bump and the pr is perfect ;)

File: tests/Functional/Admin/BrowserTest.php [hunk 6]
```diff
@@ -121,6 +121,7 @@ private function extractUniqId(Form $form): string
         \assert(\is_string($queryString));
 
         parse_str($queryString, $queryParameters);
+        \assert(\is_string($queryParameters['uniqid']));
```
Comment (eerison) [inline tests/Functional/Admin/BrowserTest.php:124]: @VincentLanglet I just let this change, because phpstan was complain about it!

Comment (VincentLanglet) [reply tests/Functional/Admin/BrowserTest.php:124]: Yes sure

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
image

**Comment by eerison** [comment]
> image

I didn't get any conflict 👀

**Comment by VincentLanglet** [comment]
Squash was working, but couldn't rebase...
