### PR TITLE
fix site create command no confirmation option

### LINKED ISSUE #903: Create site command 'no-confirmation' option does not work.
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle                  3.23.0 3.23.0 The missing Symfony Admin Generator
sonata-project/admin-search-bundle           v1.0.0 v1.0.0 Implement Search Engine (ElasticSearch) inside Sonata Admin
sonata-project/block-bundle                  3.4.0  3.4.0  Symfony SonataBlockBundle
sonata-project/cache                         1.0.7  1.0.7  Cache library
sonata-project/cache-bundle                  2.3.1  2.3.1  This bundle provides caching services
sonata-project/classification-bundle         3.3.2  3.3.2  Symfony SonataClassificationBundle
sonata-project/core-bundle                   3.5.1  3.6.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle               2.2.1  2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions           1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-mongodb-admin-bundle 3.0.0  3.0.0  Symfony Sonata / Integrate Doctrine MongoDB ODM into the SonataAdminBundle
sonata-project/doctrine-orm-admin-bundle     3.1.4  3.1.7  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle           2.2.0  2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                      1.7.1  1.7.1  Lightweight Exporter library
sonata-project/formatter-bundle              3.2.3  3.2.3  Symfony SonataFormatterBundle
sonata-project/google-authenticator          1.1.0  1.1.0  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle                   2.3.2  2.3.2  Symfony SonataIntlBundle
sonata-project/media-bundle                  3.7.0  3.7.0  Symfony SonataMediaBundle
sonata-project/news-bundle                   3.1.2  3.1.2  Symfony SonataNewsBundle
sonata-project/notification-bundle           3.2.0  3.2.0  Symfony SonataNotificationBundle
sonata-project/page-bundle                   3.5.2  3.5.2  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                    2.2.1  2.2.1  Symfony SonataSeoBundle
sonata-project/user-bundle                   3.3.0  3.5.0  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle     v2.8.2  v2.8.2  Integrates Assetic into Symfony2              
symfony/monolog-bundle     v3.1.1  v3.1.2  Symfony MonologBundle
symfony/polyfill-apcu      v1.6.0  v1.6.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.6.0  v1.6.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.6.0  v1.6.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.6.0  v1.6.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  v3.0.3  Symfony SwiftmailerBundle
symfony/symfony            v2.8.28 v3.3.10 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 5.6.31
```

## Subject

Please take a look at this line: https://github.com/sonata-project/SonataPageBundle/blob/3.x/src/Command/CreateSiteCommand.php#L34

This option is not working.

Because as I can see, the usage was removed in this commit: https://github.com/sonata-project/SonataPageBundle/commit/4c19123dbd3e6d4b854524d04e1cd62728de242d#diff-29b739ba6276841db77993efcb06dceeL107

### PR DESCRIPTION
**Pull request by codebach**
I am targeting this branch, because this needs to be fixed on this branch.

Closes #903

## Changelog
```Markdown
### Fixed
- Unused `no-confirmation` option for site create command
```

### CODE REVIEW

**Comment by core23** [comment]
Can you try to add a test for this?

**Comment by codebach** [comment]
> Can you try to add a test for this?

@core23 Done. Can we make a new release after this is merged?

File: tests/Command/CreateSiteCommandTest.php [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+    private $application;
+
+    /**
+     * @var SiteManagerInterface|ObjectProphecy
+     */
+    private $siteManager;
+
+    protected function setUp()
+    {
+        $this->siteManager = $this->prophesize('Sonata\PageBundle\Model\SiteManagerInterface');
```
Comment (OskarStark) [inline tests/Command/CreateSiteCommandTest.php]: please use `SiteManagerInterface::class` etc. where possible

Comment (codebach) [reply tests/Command/CreateSiteCommandTest.php]: This was copied from existing command tests, but I changed it to use class 👍

**Comment by codebach** [comment]
If there isn't any other thing, can we please merge this today?

**Comment by OskarStark** [comment]
Thank you @codebach 👍 

I will ask @Soullivaneuh for a release

**Comment by codebach** [comment]
Thank you @OskarStark

**Comment by OskarStark** [comment]
@codebach [3.6.0]( https://github.com/sonata-project/SonataPageBundle/releases/tag/3.6.0) was released.
