### PR TITLE
Fix CmsManagerSelector.isEditor always returns false

### LINKED ISSUE #1675: CmsManagerSelector.isEditor always returns false
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
Info from https://repo.packagist.org: #StandWithUkraine
Color legend:
- patch or minor release available - update recommended
- major release available - update possible
- up to date version

Direct dependencies required in composer.json:
sonata-project/admin-bundle              4.22.3 4.22.5 The missing Symfony Admin Generator
sonata-project/doctrine-orm-admin-bundle 4.9.1  4.10.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/media-bundle              4.5.1  4.7.0  Symfony SonataMediaBundle
sonata-project/page-bundle               4.0.0  4.1.0  This bundle provides a Site and Page management through container and block services

Transitive dependencies not required in composer.json:
sonata-project/block-bundle              4.19.0 4.20.0 Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.2.0  Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/doctrine-extensions       2.1.0  2.2.0  Doctrine2 behavioral extensions
sonata-project/exporter                  3.1.1  3.1.1  Lightweight Exporter library
sonata-project/form-extensions           1.18.0 1.18.1 Symfony form extensions
sonata-project/seo-bundle                3.5.0  3.5.0  Symfony SonataSeoBundle
sonata-project/twig-extensions           1.12.0 2.0.0  Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
Color legend:
- patch or minor release available - update recommended
- major release available - update possible
- up to date version

Direct dependencies required in composer.json:
symfony/console                    v5.4.17 v6.2.7  Eases the creation of beautiful and testable command line interfaces
symfony/debug-bundle               v5.4.11 v6.2.7  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Sy...
symfony/dependency-injection       v5.4.17 v6.2.7  Allows you to standardize and centralize the way objects are constructed in your application
symfony/dotenv                     v5.4.5  v6.2.7  Registers environment variables from a .env file
symfony/flex                       v1.19.4 v2.2.5  Composer plugin for Symfony
symfony/framework-bundle           v5.4.17 v6.2.7  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/mailer                     v5.4.17 v6.2.7  Helps sending emails
symfony/maker-bundle               v1.48.0 v1.48.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writin...
symfony/monolog-bundle             v3.8.0  v3.8.0  Symfony MonologBundle
symfony/proxy-manager-bridge       v5.4.6  v6.2.7  Provides integration for ProxyManager with various Symfony components
symfony/runtime                    v5.4.11 v6.2.7  Enables decoupling PHP applications from global state
symfony/security-bundle            v5.4.17 v6.2.7  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/serializer                 v5.4.17 v6.2.7  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats ...
symfony/stopwatch                  v5.4.13 v6.2.7  Provides a way to profile code
symfony/twig-bundle                v5.4.17 v6.2.7  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/ux-autocomplete            v2.4.0  v2.7.1  JavaScript Autocomplete functionality for Symfony
symfony/ux-dropzone                v2.4.0  v2.7.1  File input dropzones for Symfony Forms
symfony/ux-live-component          v2.4.0  v2.7.1  Live components for Symfony
symfony/ux-swup                    v2.4.0  v2.7.1  Swup integration for Symfony
symfony/ux-twig-component          v2.4.0  v2.7.1  Twig components for Symfony
symfony/validator                  v5.4.17 v6.2.7  Provides tools to validate values
symfony/web-profiler-bundle        v5.4.17 v6.2.7  Provides a development tool that gives detailed information about the execution of any request
symfony/webpack-encore-bundle      v1.16.0 v1.16.1 Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v5.4.17 v6.2.7  Loads and dumps YAML files

Transitive dependencies not required in composer.json:
symfony/asset                      v5.4.13 v6.2.7  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/cache                      v5.4.18 v6.2.7  Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts            v2.5.2  v3.2.1  Generic abstractions related to caching
symfony/config                     v5.4.11 v6.2.7  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/css-selector               v5.4.17 v6.2.7  Converts CSS selectors to XPath expressions
symfony/deprecation-contracts      v3.2.0  v3.2.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.4.17 v6.2.7  Provides integration for Doctrine with various Symfony components
symfony/error-handler              v5.4.17 v6.2.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.4.17 v6.2.7  Provides tools that allow your application components to communicate with each other by dispatching events and listenin...
symfony/event-dispatcher-contracts v3.2.0  v3.2.1  Generic abstractions related to dispatching event
symfony/expression-language        v5.4.14 v6.2.7  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.4.13 v6.2.7  Provides basic utilities for the filesystem
symfony/finder                     v5.4.17 v6.2.7  Finds files and directories via an intuitive fluent interface
symfony/form                       v5.4.17 v6.2.7  Allows to easily create, process and reuse HTML forms
symfony/http-client                v5.4.17 v6.2.7  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.5.2  v3.2.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.4.17 v6.2.7  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.4.18 v6.2.7  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.4.15 v6.2.7  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mime                       v5.4.17 v6.2.7  Allows manipulating MIME messages
symfony/monolog-bridge             v5.4.17 v6.2.7  Provides integration for Monolog with various Symfony components
symfony/options-resolver           v5.4.11 v6.2.7  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v5.4.11 v6.2.7  Provides password hashing utilities
symfony/polyfill-intl-grapheme     v1.27.0 v1.27.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.27.0 v1.27.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.27.0 v1.27.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.27.0 v1.27.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.27.0 v1.27.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.27.0 v1.27.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.27.0 v1.27.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.27.0 v1.27.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                    v5.4.11 v6.2.7  Executes commands in sub-processes
symfony/property-access            v5.4.15 v6.2.7  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.4.17 v6.2.7  Extracts information about PHP class' properties using metadata of popular sources
symfony/routing                    v5.4.17 v6.2.7  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.3.2  v3.3.2  Symfony Security Component - ACL (Access Control List)
symfony/security-core              v5.4.15 v6.2.7  Symfony Security Component - Core Library
symfony/security-csrf              v5.4.11 v6.2.7  Symfony Security Component - CSRF Library
symfony/security-guard             v5.4.13 v5.4.21 Symfony Security Component - Guard
symfony/security-http              v5.4.17 v6.2.7  Symfony Security Component - HTTP Integration
symfony/service-contracts          v2.5.2  v3.2.1  Generic abstractions related to writing services
symfony/string                     v5.4.17 v6.2.7  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/templating                 v5.4.11 v6.2.7  Provides all the tools needed to build any kind of template system
symfony/translation                v5.4.14 v6.2.7  Provides tools to internationalize your application
symfony/translation-contracts      v2.5.2  v3.2.1  Generic abstractions related to translation
symfony/twig-bridge                v5.4.17 v6.2.7  Provides integration for Twig with various Symfony components
symfony/var-dumper                 v5.4.17 v6.2.7  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.4.17 v6.2.7  Allows exporting any serializable PHP data structure to plain PHP code
```

</p>
</details>

#### PHP version

```
$ php -v
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.10, Copyright (c), by Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans
```

## Subject

When logged with a page admin user account and editing a block from the admin panel, the changes doesn't appear without creating a publication

## Steps to reproduce
Set direct_publication configuration to false, edit a block from page admin panel and go to the target page

## Expected results
View changes directly

## Actual results
No changes

After searching in the code, I found that a parameter 'sonata/page/isEditor' should be set to true in session.
An event listener is mapped on security.interactive_login wich doesn't exists on last symfony versions.
The event migration seems to be up to date with logout but not with login:

```php
<?php
$containerConfigurator->services()
 //...
         ->set('sonata.page.cms_manager_selector', CmsManagerSelector::class)
            ->public()
            ->tag('kernel.event_listener', [
                'event' => 'security.interactive_login', //<-- should be LoginSuccessEvent::class ?
                'method' => 'onSecurityInteractiveLogin' , //<-- should be  onLogin ?
            ])
            ->tag('kernel.event_listener', [
                'event' => LogoutEvent::class,
                'method' => 'onLogout',
            ])
            ->args([
                new ReferenceConfigurator('sonata.page.cms.page'),
                new ReferenceConfigurator('sonata.page.cms.snapshot'),
                new ReferenceConfigurator('sonata.page.admin.page'),
                new ReferenceConfigurator('security.token_storage'),
                new ReferenceConfigurator('request_stack'),
            ])
 
```

### PR DESCRIPTION
**Pull request by tdumalin**
## Subject

Migrate security.interactive_login event to LoginSuccessEvent

Symfony security doesn't use security.interactive_login since v5.1:
[https://symfony.com/blog/new-in-symfony-5-1-updated-security-system](https://symfony.com/blog/new-in-symfony-5-1-updated-security-system)

So the 'sonata/page/isEditor' session item is never defined and PAGE_ADMIN can't see the last modification on their  page without publishing when sonata_page.direct_publication is set to false

I am targeting this branch, because this is the default branch.

Closes #1675 .

## Changelog

```markdown
### Fixed
-  `CmsManagerSelector::isEditor` always returns false

### Deprecated
- `CmsManagerSelector::onSecurityInteractiveLogin`
```

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Do you think there is an easy test functional test to add ?

File: src/CmsManager/CmsManagerSelector.php [hunk 1]
```diff
@@ -63,7 +63,7 @@ public function isEditor(): bool
             && false !== $request->getSession()->get('sonata/page/isEditor', false);
     }
 
-    public function onSecurityInteractiveLogin(InteractiveLoginEvent $event): void
```
Comment (VincentLanglet) [inline src/CmsManager/CmsManagerSelector.php:66]: This renaming is unfortunately a BC break. (someone could call manually onSecurityInteractiveLogin)

What we should do is:
- keeping the old `onSecurityInteractiveLogin` method but deprecating it.
- creating a new `onLoginSuccess` method.

File: src/Resources/config/page.php [hunk 2]
```diff
@@ -133,8 +134,8 @@
         ->set('sonata.page.cms_manager_selector', CmsManagerSelector::class)
             ->public()
             ->tag('kernel.event_listener', [
-                'event' => 'security.interactive_login',
-                'method' => 'onSecurityInteractiveLogin',
+                'event' => LoginSuccessEvent::class,
+                'method' => 'onLoginSuccess',
             ])
```
Comment (VincentLanglet) [inline src/Resources/config/page.php]: Same here, this is a BC break cause someone could dispatch manually the old event, what we can do is having both:
```
// NEXT_MAJOR: Stop listening 'security.interactive_login'.
->tag('kernel.event_listener', [
                'event' => 'security.interactive_login',
                'method' => 'onSecurityInteractiveLogin',
            ])
->tag('kernel.event_listener', [
                'event' => LoginSuccessEvent::class,
                'method' => 'onLoginSuccess',
            ])
```

**Review by VincentLanglet — CHANGES_REQUESTED** [review]

**Comment by tdumalin** [comment]
Here you go, 

For the tests I don't think there is an easy functionnal test to do because the loginUser method provider in test:
[https://github.com/symfony/symfony/blob/7.0/src/Symfony/Bundle/FrameworkBundle/KernelBrowser.php#:~:text=function%20loginUser](https://github.com/symfony/symfony/blob/7.0/src/Symfony/Bundle/FrameworkBundle/KernelBrowser.php#:~:text=function%20loginUser)

doesn't seem to trigger login event. Maybe a phpunit test with the dispatcher ?

**Review by VincentLanglet — DISMISSED** [review]

**Comment by VincentLanglet** [comment]
@tdumalin Can you solve the lint build ? thanks

**Comment by tdumalin** [comment]
I didn't see any difference on the failed build between the proposal and the actual code, can you help me ?

**Review by VincentLanglet — DISMISSED** [review]

**Comment by VincentLanglet** [comment]
> I didn't see any difference on the failed build between the proposal and the actual code, can you help me ?

Private method should be last in the class.

Public, then protected, then private ; I think it's this.

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks !
