### PR TITLE
Fix Breadcrumbs into the page

### LINKED ISSUE #1497: Breadcrumbs are not appearing into the pages
In 4.x branch the homepage looks strange.

it's the page for 3.x branch
Screenshot 2022-07-26 at 16 46 10

it's the same page for 4.x branch

Screenshot 2022-07-26 at 16 58 28

### PR DESCRIPTION
**Pull request by eerison**
## Subject

I am targeting this branch, because it was breaking the pipeline in 4.x branch.

Closes #1497

## Changelog

```markdown
### Changed
- Changed `page` context to `sonata.page.block.breadcrumb` used in `src/Resources/views/layout.html.twig` file
```

### CODE REVIEW

**Comment by eerison** [comment]
Hey @VincentLanglet 

it's the correct code for the test, But as expected it'll fail because the breadcrumbs are not returning into the page!

is it fine wait until I find out the issue, or should we skip this test and merge, and after that I open a new PR with the fix for this bug?

**Comment by eerison** [comment]
I guess this problem is related with: https://github.com/sonata-project/SonataPageBundle/blob/4.x/src/Block/BreadcrumbBlockService.php

the getMenu was not used, anymore :/

**Comment by VincentLanglet** [comment]
> Hey @VincentLanglet
> 
> it's the correct code for the test, But as expected it'll fail because the breadcrumbs are not returning into the page!
> 
> is it fine wait until I find out the issue, or should we skip this test and merge, and after that I open a new PR with the fix for this bug?

Sure, we can wait the fix

**Comment by eerison** [comment]
Ok as I was suspecting this bug was introduced in `SEO refactoring`

https://github.com/sonata-project/SonataPageBundle/pull/1483/files#diff-f0461df8f4a53195f2b565ad37746df1e8076ff748edb18c3e2689581f2db4caR87

is there any reason to use this return `sonata.page.block.breadcrumb`?

because it was passing `page` value before.

I changed the context passed by template to `sonata.page.block.breadcrumb`, I would say it make more sense then `page`

But I just would like to know if there is some thing else for this `getName` method with this value!

cc @Daric971

**Comment by eerison** [comment]
Hey @jordisala1991 could you help me here with this phpstan errors?

**Comment by VincentLanglet** [comment]
ProxyQuery is now generic. 
```
ProxyQueryInterface<object>
```

And for 
```
Parameter #1 $twig of class Sonata\PageBundle\Page\TemplateManager constructor expects Twig\Environment, object|null given.
```
You have to assert
```
$twig = $container->get('twig');
\assert($twig instanceof Environment)
```

File: src/Admin/SharedBlockAdmin.php [hunk 1]
```diff
@@ -38,6 +38,9 @@ protected function generateBaseRouteName(bool $isChildAdmin = false): string
         return sprintf('%s_%s', parent::generateBaseRouteName($isChildAdmin), 'shared');
     }
 
+    /**
+     * @param ProxyQueryInterface<object> $query
+     */
```
Comment (VincentLanglet) [inline src/Admin/SharedBlockAdmin.php]: You don't need it here.
```suggestion
```

**Review by VincentLanglet — CHANGES_REQUESTED** [review]

File: src/Admin/SharedBlockAdmin.php (hunk 1 above)
Comment (eerison) [reply src/Admin/SharedBlockAdmin.php]: I'm trying to solve a lint issue in this. file :'(

**Comment by eerison** [comment]
Ok I got those 2 errors

```
Error: src/Admin/SharedBlockAdmin.php:41:68: MoreSpecificReturnType: The declared return type 'Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>' for Sonata\PageBundle\Admin\SharedBlockAdmin::configureQuery is more specific than the inferred return type 'Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery&Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>' (see https://psalm.dev/070)

Error: src/Admin/SharedBlockAdmin.php:50:16: LessSpecificReturnStatement: The type 'Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery&Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>' is more general than the declared return type 'Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>' for Sonata\PageBundle\Admin\SharedBlockAdmin::configureQuery (see https://psalm.dev/12[9](https://github.com/sonata-project/SonataPageBundle/runs/7948691625?check_suite_focus=true#step:5:10))
🐑 results sent to shepherd.dev 🐑
Error: Process completed with exit code 2.
```

any idea how to solve @VincentLanglet

**Comment by VincentLanglet** [comment]
> MoreSpecificReturnType: The declared return type 'Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>' for Sonata\PageBundle\Admin\SharedBlockAdmin::configureQuery is more specific than the inferred return type 'Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery&Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>

Isn't a bug ?

`Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>`
is considered as more specific than
`Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery&Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>`
but
`Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery&Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>`
is
`Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery`
AND
`Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>`

So to me
`Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery&Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>`
is more specific than `Sonata\AdminBundle\Datagrid\ProxyQueryInterface<Sonata\PageBundle\Model\PageBlockInterface>` not the opposite.

Do you mind looking in the issues/creating an issue on https://github.com/vimeo/psalm/issues ?

Moreover, if it's a real issue, I think it would have been reported by phpstan.

**Comment by eerison** [comment]
Yeah there is a bug, But I guess it's not related with psalm

Because the code was importing a different ProxyQuery (from Datagrid), But the method returns ProxyQuery from admin

File: src/Admin/SharedBlockAdmin.php [hunk 2]
```diff
@@ -14,11 +14,11 @@
 namespace Sonata\PageBundle\Admin;
 
 use Sonata\AdminBundle\Datagrid\ListMapper;
-use Sonata\AdminBundle\Datagrid\ProxyQueryInterface;
 use Sonata\AdminBundle\Form\FormMapper;
+use Sonata\AdminBundle\Datagrid\ProxyQueryInterface;
 use Sonata\BlockBundle\Block\Service\EditableBlockService;
 use Sonata\BlockBundle\Model\BlockInterface;
-use Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery;
+use Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQueryInterface as DatagridProxyInterface;
```
Comment (VincentLanglet) [inline src/Admin/SharedBlockAdmin.php]:
```suggestion
use Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQueryInterface as ORMProxyInterface;
```
will be better.

File: src/Admin/SharedBlockAdmin.php [hunk 3]
```diff
@@ -38,9 +38,13 @@ protected function generateBaseRouteName(bool $isChildAdmin = false): string
...
+     * @param DatagridProxyInterface<PageBlockInterface> $query
+     * @return DatagridProxyInterface<PageBlockInterface>&ProxyQueryInterface<PageBlockInterface>
+     */
     protected function configureQuery(ProxyQueryInterface $query): ProxyQueryInterface
     {
-        \assert($query instanceof ProxyQuery);
+        \assert($query instanceof DatagridProxyInterface);
 
         // Filter on blocks without page and parents
         $rootAlias = current($query->getRootAliases());
```
Comment (VincentLanglet) [inline src/Admin/SharedBlockAdmin.php]: all those methods doesn't exists in the ProxyQueryInterface.

But you can solve all the issue by doing

`$query->getQueryBuilder()->getRootAliases()` and so on.

**Review by VincentLanglet — CHANGES_REQUESTED** [review]

**Comment by VincentLanglet** [comment]
> Yeah there is a bug, But I guess it's not related with psalm
> 
> Because the code was importing a different ProxyQuery (from Datagrid), But the method returns ProxyQuery from admin

That's not an issue.
The ProxyQuery implements the ORMProxyQueryInterface which implements ProxyQueryInterface from AdminBundle.
So we do return a ProxyQueryInterface.

I still believe it's an issue with psalm.

File: src/Admin/SharedBlockAdmin.php [hunk 4]
```diff
@@ -38,14 +38,19 @@ protected function generateBaseRouteName(bool $isChildAdmin = false): string
         return sprintf('%s_%s', parent::generateBaseRouteName($isChildAdmin), 'shared');
     }
 
-    protected function configureQuery(ProxyQueryInterface $query): ProxyQueryInterface
+    /**
+     * @param ORMProxyInterface<PageBlockInterface> $query
```
Comment (VincentLanglet) [inline src/Admin/SharedBlockAdmin.php:42]: You cannot add it to phpdoc for contravariance issues.

Comment (eerison) [reply src/Admin/SharedBlockAdmin.php:42]: I was ondering, why do we need this check

`\assert($query instanceof ORMProxyInterface);`, if the ProxyInterface has everything to make this method works

Comment (VincentLanglet) [reply src/Admin/SharedBlockAdmin.php:42]: The ProxyQueryInteface doesn't have getQueryBuilder ; it only works for the ORM one.

Like I said, it's an issue with psalm.
Just add PsalmSuppress MoreSpecificReturnType, LessSpecificReturnStatement with a like to https://github.com/vimeo/psalm/issues/8429

Comment (eerison) [reply src/Admin/SharedBlockAdmin.php:42]: Ok But What do I do until this issue be fixed? should I ignore this for now, and remove the comment after it be fixed there?

Comment (VincentLanglet) [reply src/Admin/SharedBlockAdmin.php:42]: The psalm suppress will ignore the error

Comment (eerison) [reply src/Admin/SharedBlockAdmin.php:42]: what do you mean  "psalm suppress"

File: src/Admin/SharedBlockAdmin.php [hunk 5]
```diff
@@ -38,14 +38,19 @@ protected function generateBaseRouteName(bool $isChildAdmin = false): string
...
+     * @return ORMProxyInterface<PageBlockInterface>
+     */
```
Comment (VincentLanglet) [inline src/Admin/SharedBlockAdmin.php]:
```suggestion
    /**
     * @psalm-suppress LessSpecificReturnStatement, MoreSpecificReturnType
     *
     * @see https://github.com/vimeo/psalm/issues/8429
     */
```

**Review by VincentLanglet — CHANGES_REQUESTED** [review]

File: src/Admin/SharedBlockAdmin.php (hunk 5 above)
Comment (eerison) [reply src/Admin/SharedBlockAdmin.php]: hmmm I got it! 👍🏼

**Review by VincentLanglet — APPROVED** [review]

File: src/Controller/PageAdminController.php [hunk 6]
```diff
@@ -54,6 +54,8 @@ public static function getSubscribedServices(): array
     }
 
     /**
+     * @param ProxyQueryInterface<object> $query
```
Comment (jordisala1991) [inline src/Controller/PageAdminController.php:57]: But if we know this is batch for pages, shouldnt this objet be PageInterface?

cc @VincentLanglet

File: src/Controller/SnapshotAdminController.php [hunk 7]
```diff
@@ -35,6 +35,8 @@ public static function getSubscribedServices(): array
     }
 
     /**
+     * @param ProxyQueryInterface<object> $query
```
Comment (jordisala1991) [inline src/Controller/SnapshotAdminController.php:38]: Same but with SnapshotInterface

File: src/Resources/views/layout.html.twig [hunk 8]
```diff
@@ -18,8 +18,8 @@ file that was distributed with this source code.
             </div>
 
             {% block sonata_page_breadcrumb %}
-                <div class="row">
-                    {{ sonata_block_render_event('breadcrumb', { 'context': 'page', 'current_uri': app.request.requestUri }) }}
+                <div class="row page-breadcrumb">
+                    {{ sonata_block_render_event('breadcrumb', { 'context': 'sonata.page.block.breadcrumb', 'current_uri': app.request.requestUri }) }}
```
Comment (jordisala1991) [inline src/Resources/views/layout.html.twig:22]: do we know why this context changed? should we revert something somewhere?

Also if this code changes is there any docs to update?

File: tests/Page/TemplateManagerTest.php [hunk 9]
```diff
@@ -136,6 +144,51 @@ public function testRenderResponseWithDefaultParameters(): void
...
+        // Mocking snapshot
+        $pageMock = $this->createMock(PageInterface::class);
+        $pageMock->method('getName')->willReturn('Foo');
+        $pageMock->method('getParents')->willReturn([]);
+        $pageMock->method('getUrl')->willReturn('/');
+
+        // Mock Snapshot manager
+        $snapshotManagerMock = $this->createMock(SnapshotManagerInterface::class);
+        $transformerMock = $this->createMock(TransformerInterface::class);
+        $cmsSnapshotManagerMock = new CmsSnapshotManager($snapshotManagerMock, $transformerMock);
```
Comment (jordisala1991) [inline tests/Page/TemplateManagerTest.php:167]: I recommend to not name variables with mock suffix , this one is a mistake for example, it is not a mock

Comment (eerison) [reply tests/Page/TemplateManagerTest.php:167]: true :/

File: src/Resources/views/layout.html.twig (hunk 8 above)
Comment (eerison) [reply src/Resources/views/layout.html.twig:22]: check this comment please : https://github.com/sonata-project/SonataPageBundle/pull/1564#issuecomment-1222008738

Comment (eerison) [reply src/Resources/views/layout.html.twig:22]: But this bug was introduced here: https://github.com/sonata-project/SonataPageBundle/pull/1483/files#diff-f0461df8f4a53195f2b565ad37746df1e8076ff748edb18c3e2689581f2db4caR87

I guess he was just following how the stuffs were made in others parts, But in 3.x it was using `page`

and when added this method, it was changed!

I choose to use `sonata.page.block.breadcrumb` because it's more explainable then `page`, But yes, It's a BC!

because if someone is using  `sonata_block_render_event` passing page, it won't work!

I could back to `page`, But I guess it's not the correct correct for  `breadcrumb`, `sonata.page.block.breadcrumb` make more sense!

File: src/Controller/PageAdminController.php (hunk 6 above)
Comment (VincentLanglet) [reply src/Controller/PageAdminController.php:57]: Indeed

File: src/Controller/SnapshotAdminController.php (hunk 7 above)
Comment (VincentLanglet) [reply src/Controller/SnapshotAdminController.php:38]: Indeed

File: src/Resources/views/layout.html.twig (hunk 8 above)
Comment (jordisala1991) [reply src/Resources/views/layout.html.twig:22]: I made a mistake there, imo it should be page

Comment (eerison) [reply src/Resources/views/layout.html.twig:22]: well we can back this for page :), 

I'll open a PR for this ;)

Comment (jordisala1991) [reply src/Resources/views/layout.html.twig:22]: Yes if you can open a PR to fix the things I mentioned it would be great :) thanks!

Comment (VincentLanglet) [reply src/Resources/views/layout.html.twig:22]: I opened https://github.com/sonata-project/SonataPageBundle/pull/1570
