### PR TITLE
Fix block creation

### LINKED ISSUE #1586: Make page blocks works or remove if it is not used
When I'm trying to use the page blocks, some of them are crashing the page

#### Blocks

- [x] Children page core
- [x] Breadcrumb
- [x] Shared blocks
<details><summary>Chieldren page core</summary>
<p>

```
Twig\Error\RuntimeError:
An exception has been thrown during the rendering of a template ("An exception occurred while executing a query: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 1: ...hot p0_ WHERE (p0_.parent_id = $1 AND p0_.enabled = 1) AND (...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.").

  at vendor/sonata-project/page-bundle/src/Resources/views/Block/block_core_children_pages.html.twig:31
  at Twig\Template->displayBlock('block', array('page' => object(SnapshotPageProxy), 'block' => object(SonataPageBlock), 'settings' => array('use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_core_children_pages.html.twig', 'ttl' => 86400, 'current' => true, 'pageId' => null, 'title' => 'Page core title', 'translation_domain' => null, 'icon' => null, 'class' => null), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block' => array(object(__TwigTemplate_1c47d4e460b4e91c9150fca0d75bf688), 'block_block')))
     (var/cache/dev/twig/05/0510d582990bbf1fa7da00c303877039.php:66)
  at __TwigTemplate_d435fb943812d16a601ff59c0a533e59->doDisplay(array('page' => object(SnapshotPageProxy), 'block' => object(SonataPageBlock), 'settings' => array('use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_core_children_pages.html.twig', 'ttl' => 86400, 'current' => true, 'pageId' => null, 'title' => 'Page core title', 'translation_domain' => null, 'icon' => null, 'class' => null), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block' => array(object(__TwigTemplate_1c47d4e460b4e91c9150fca0d75bf688), 'block_block')))
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling(array('page' => object(SnapshotPageProxy), 'block' => object(SonataPageBlock), 'settings' => array('use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_core_children_pages.html.twig', 'ttl' => 86400, 'current' => true, 'pageId' => null, 'title' => 'Page core title', 'translation_domain' => null, 'icon' => null, 'class' => null), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block' => array(object(__TwigTemplate_1c47d4e460b4e91c9150fca0d75bf688), 'block_block')))
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('page' => object(SnapshotPageProxy), 'block' => object(SonataPageBlock), 'settings' => array('use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_core_children_pages.html.twig', 'ttl' => 86400, 'current' => true, 'pageId' => null, 'title' => 'Page core title', 'translation_domain' => null, 'icon' => null, 'class' => null), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block' => array(object(__TwigTemplate_1c47d4e460b4e91c9150fca0d75bf688), 'block_block')))
     (var/cache/dev/twig/06/0654a8601003e8648d52ff9a38a21237.php:47)
  at __TwigTemplate_1c47d4e460b4e91c9150fca0d75bf688->doDisplay(array('page' => object(SnapshotPageProxy), 'block' => object(SonataPageBlock), 'settings' => array('use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_core_children_pages.html.twig', 'ttl' => 86400, 'current' => true, 'pageId' => null, 'title' => 'Page core title', 'translation_domain' => null, 'icon' => null, 'class' => null), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block' => array(object(__TwigTemplate_1c47d4e460b4e91c9150fca0d75bf688), 'block_block')))
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling(array('page' => object(SnapshotPageProxy), 'block' => object(SonataPageBlock), 'settings' => array('use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_core_children_pages.html.twig', 'ttl' => 86400, 'current' => true, 'pageId' => null, 'title' => 'Page core title', 'translation_domain' => null, 'icon' => null, 'class' => null), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block' => array(object(__TwigTemplate_1c47d4e460b4e91c9150fca0d75bf688), 'block_block')))
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('page' => object(SnapshotPageProxy), 'block' => object(SonataPageBlock), 'settings' => array('use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_core_children_pages.html.twig', 'ttl' => 86400, 'current' => true, 'pageId' => null, 'title' => 'Page core title', 'translation_domain' => null, 'icon' => null, 'class' => null)))
     (vendor/twig/twig/src/Template.php:379)
  at Twig\Template->render(array('page' => object(SnapshotPageProxy), 'block' => object(SonataPageBlock), 'settings' => array('use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_core_children_pages.html.twig', 'ttl' => 86400, 'current' => true, 'pageId' => null, 'title' => 'Page core title', 'translation_domain' => null, 'icon' => null, 'class' => null)), array())
     (vendor/twig/twig/src/TemplateWrapper.php:40)
  at Twig\TemplateWrapper->render(array('page' => object(SnapshotPageProxy), 'block' => object(SonataPageBlock), 'settings' => array('use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_core_children_pages.html.twig', 'ttl' => 86400, 'current' => true, 'pageId' => null, 'title' => 'Page core title', 'translation_domain' => null, 'icon' => null, 'class' => null)))
     (vendor/twig/twig/src/Environment.php:277)
  at Twig\Environment->render('@SonataPage/Block/block_core_children_pages.html.twig', array('page' => object(SnapshotPageProxy), 'block' => object(SonataPageBlock), 'settings' => array('use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_core_children_pages.html.twig', 'ttl' => 86400, 'current' => true, 'pageId' => null, 'title' => 'Page core title', 'translation_domain' => null, 'icon' => null, 'class' => null)))
     (vendor/sonata-project/block-bundle/src/Block/Service/AbstractBlockService.php:43)
  at Sonata\BlockBundle\Block\Service\AbstractBlockService->renderResponse('@SonataPage/Block/block_core_children_pages.html.twig', array('page' => object(SnapshotPageProxy), 'block' => object(SonataPageBlock), 'settings' => array('use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_core_children_pages.html.twig', 'ttl' => 86400, 'current' => true, 'pageId' => null, 'title' => 'Page core title', 'translation_domain' => null, 'icon' => null, 'class' => null)), object(Response))
     (vendor/sonata-project/page-bundle/src/Block/ChildrenPagesBlockService.php:94)
  at Sonata\PageBundle\Block\ChildrenPagesBlockService->execute(object(BlockContext), object(Response))
     (vendor/sonata-project/block-bundle/src/Block/BlockRenderer.php:70)
  at Sonata\BlockBundle\Block\BlockRenderer->render(object(BlockContext))
     (vendor/sonata-project/block-bundle/src/Templating/Helper/BlockHelper.php:450)
  at Sonata\BlockBundle\Templating\Helper\BlockHelper->render(object(SonataPageBlock), array())
     (vendor/sonata-project/page-bundle/src/Twig/Extension/PageExtension.php:194)
  at Sonata\PageBundle\Twig\Extension\PageExtension->renderBlock(object(SonataPageBlock))
     (var/cache/dev/twig/ff/ff2bc35fd4f52c62a44b838fef1377e5.php:69)
  at __TwigTemplate_ee14b3162ccd64b865d6db649e296aee->block_block_child_render(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin), '_parent' => array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), '_seq' => array(object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock)), 'loop' => array('parent' => array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), 'index0' => 5, 'index' => 6, 'first' => false, 'revindex0' => 0, 'revindex' => 1, 'length' => 6, 'last' => true), 'child' => object(SonataPageBlock), '_key' => 5), array('block' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block'), 'block_class' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_class'), 'block_role' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_role'), 'block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (vendor/twig/twig/src/Template.php:171)
  at Twig\Template->displayBlock('block_child_render', array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin), '_parent' => array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), '_seq' => array(object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock)), 'loop' => array('parent' => array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), 'index0' => 5, 'index' => 6, 'first' => false, 'revindex0' => 0, 'revindex' => 1, 'length' => 6, 'last' => true), 'child' => object(SonataPageBlock), '_key' => 5), array('block' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block'), 'block_class' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_class'), 'block_role' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_role'), 'block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (var/cache/dev/twig/a7/a71e2e497387d0ff6dcc6d582691dca1.php:139)
  at __TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f->block_block(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin), '_parent' => array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), '_seq' => array(object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock), object(SonataPageBlock)), 'loop' => array('parent' => array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), 'index0' => 5, 'index' => 6, 'first' => false, 'revindex0' => 0, 'revindex' => 1, 'length' => 6, 'last' => true), 'child' => object(SonataPageBlock), '_key' => 5), array('block' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block'), 'block_class' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_class'), 'block_role' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_role'), 'block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (vendor/twig/twig/src/Template.php:171)
  at Twig\Template->displayBlock('block', array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block'), 'block_class' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_class'), 'block_role' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_role'), 'block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (var/cache/dev/twig/05/0510d582990bbf1fa7da00c303877039.php:66)
  at __TwigTemplate_d435fb943812d16a601ff59c0a533e59->doDisplay(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block'), 'block_class' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_class'), 'block_role' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_role'), 'block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block'), 'block_class' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_class'), 'block_role' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_role'), 'block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block_class' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_class'), 'block_role' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_role'), 'block' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block'), 'block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (var/cache/dev/twig/a7/a71e2e497387d0ff6dcc6d582691dca1.php:50)
  at __TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f->doDisplay(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block_class' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_class'), 'block_role' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_role'), 'block' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block'), 'block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block_class' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_class'), 'block_role' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block_role'), 'block' => array(object(__TwigTemplate_ffd0a4617d33634b0a7d9715eed89b7f), 'block_block'), 'block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (var/cache/dev/twig/ff/ff2bc35fd4f52c62a44b838fef1377e5.php:48)
  at __TwigTemplate_ee14b3162ccd64b865d6db649e296aee->doDisplay(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content'), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('block_child_render' => array(object(__TwigTemplate_ee14b3162ccd64b865d6db649e296aee), 'block_block_child_render')))
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content')))
     (vendor/twig/twig/src/Template.php:379)
  at Twig\Template->render(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content')), array())
     (vendor/twig/twig/src/TemplateWrapper.php:40)
  at Twig\TemplateWrapper->render(array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content')))
     (vendor/twig/twig/src/Environment.php:277)
  at Twig\Environment->render('@SonataPage/Block/block_container.html.twig', array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content')))
     (vendor/sonata-project/block-bundle/src/Block/Service/AbstractBlockService.php:43)
  at Sonata\BlockBundle\Block\Service\AbstractBlockService->renderResponse('@SonataPage/Block/block_container.html.twig', array('block' => object(SonataPageBlock), 'decorator' => array('pre' => '', 'post' => ''), 'settings' => array('layout' => '{{ CONTENT }}', 'class' => '', 'use_cache' => true, 'extra_cache_keys' => array(), 'attr' => array(), 'template' => '@SonataPage/Block/block_container.html.twig', 'ttl' => 86400, 'code' => 'content')), object(Response))
     (vendor/sonata-project/page-bundle/src/Block/ContainerBlockService.php:81)
  at Sonata\PageBundle\Block\ContainerBlockService->execute(object(BlockContext), object(Response))
     (vendor/sonata-project/block-bundle/src/Block/BlockRenderer.php:70)
  at Sonata\BlockBundle\Block\BlockRenderer->render(object(BlockContext))
     (vendor/sonata-project/block-bundle/src/Templating/Helper/BlockHelper.php:450)
  at Sonata\BlockBundle\Templating\Helper\BlockHelper->render(object(SonataPageBlock), array())
     (vendor/sonata-project/page-bundle/src/Twig/Extension/PageExtension.php:194)
  at Sonata\PageBundle\Twig\Extension\PageExtension->renderBlock(object(SonataPageBlock), array())
     (vendor/sonata-project/page-bundle/src/Twig/Extension/PageExtension.php:178)
  at Sonata\PageBundle\Twig\Extension\PageExtension->renderContainer('content', object(SnapshotPageProxy))
     (var/cache/dev/twig/ec/ecd8f078e1dd6cf1a7c7a65896ddc021.php:216)
  at __TwigTemplate_2aa42510ab6c10468858721df8069038->block_page_content(array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin), 'content' => ''), array('sonata_page_html_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_html_tag'), 'sonata_page_head' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_head'), 'sonata_page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_stylesheets'), 'page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_stylesheets'), 'sonata_page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_javascripts'), 'page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_javascripts'), 'sonata_page_body_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_body_tag'), 'sonata_page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_top_bar'), 'page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_top_bar'), 'sonata_page_container' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_container'), 'page_container' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_container'), 'sonata_page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_asset_footer'), 'page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_asset_footer'), 'sonata_page_breadcrumb' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_breadcrumb'), 'page_content' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_page_content')))
     (vendor/twig/twig/src/Template.php:171)
  at Twig\Template->displayBlock('page_content', array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('sonata_page_html_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_html_tag'), 'sonata_page_head' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_head'), 'sonata_page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_stylesheets'), 'page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_stylesheets'), 'sonata_page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_javascripts'), 'page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_javascripts'), 'sonata_page_body_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_body_tag'), 'sonata_page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_top_bar'), 'page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_top_bar'), 'sonata_page_container' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_container'), 'page_container' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_container'), 'sonata_page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_asset_footer'), 'page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_asset_footer'), 'sonata_page_breadcrumb' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_breadcrumb'), 'page_content' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_page_content')))
     (var/cache/dev/twig/ec/ecd8f078e1dd6cf1a7c7a65896ddc021.php:110)
  at __TwigTemplate_2aa42510ab6c10468858721df8069038->block_sonata_page_container(array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('sonata_page_html_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_html_tag'), 'sonata_page_head' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_head'), 'sonata_page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_stylesheets'), 'page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_stylesheets'), 'sonata_page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_javascripts'), 'page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_javascripts'), 'sonata_page_body_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_body_tag'), 'sonata_page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_top_bar'), 'page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_top_bar'), 'sonata_page_container' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_container'), 'page_container' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_container'), 'sonata_page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_asset_footer'), 'page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_asset_footer'), 'sonata_page_breadcrumb' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_breadcrumb'), 'page_content' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_page_content')))
     (vendor/twig/twig/src/Template.php:171)
  at Twig\Template->displayBlock('sonata_page_container', array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('sonata_page_html_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_html_tag'), 'sonata_page_head' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_head'), 'sonata_page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_stylesheets'), 'page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_stylesheets'), 'sonata_page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_javascripts'), 'page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_javascripts'), 'sonata_page_body_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_body_tag'), 'sonata_page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_top_bar'), 'page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_top_bar'), 'sonata_page_container' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_container'), 'page_container' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_container'), 'sonata_page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_asset_footer'), 'page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_asset_footer'), 'sonata_page_breadcrumb' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_breadcrumb'), 'page_content' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_page_content')))
     (var/cache/dev/twig/17/17de26996b008eaa3c0e74715c963c0d.php:74)
  at __TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1->doDisplay(array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('sonata_page_html_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_html_tag'), 'sonata_page_head' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_head'), 'sonata_page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_stylesheets'), 'page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_stylesheets'), 'sonata_page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_javascripts'), 'page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_javascripts'), 'sonata_page_body_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_body_tag'), 'sonata_page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_top_bar'), 'page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_top_bar'), 'sonata_page_container' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_container'), 'page_container' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_container'), 'sonata_page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_asset_footer'), 'page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_asset_footer'), 'sonata_page_breadcrumb' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_breadcrumb'), 'page_content' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_page_content')))
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling(array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('sonata_page_html_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_html_tag'), 'sonata_page_head' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_head'), 'sonata_page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_stylesheets'), 'page_stylesheets' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_stylesheets'), 'sonata_page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_javascripts'), 'page_javascripts' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_javascripts'), 'sonata_page_body_tag' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_body_tag'), 'sonata_page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_top_bar'), 'page_top_bar' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_top_bar'), 'sonata_page_container' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_container'), 'page_container' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_container'), 'sonata_page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_sonata_page_asset_footer'), 'page_asset_footer' => array(object(__TwigTemplate_81babb41dd30e9fbdc438bfadc8a1fc1), 'block_page_asset_footer'), 'sonata_page_breadcrumb' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_breadcrumb'), 'page_content' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_page_content')))
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('sonata_page_container' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_container'), 'sonata_page_breadcrumb' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_breadcrumb'), 'page_content' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_page_content')))
     (var/cache/dev/twig/ec/ecd8f078e1dd6cf1a7c7a65896ddc021.php:50)
  at __TwigTemplate_2aa42510ab6c10468858721df8069038->doDisplay(array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('sonata_page_container' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_container'), 'sonata_page_breadcrumb' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_breadcrumb'), 'page_content' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_page_content')))
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling(array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array('sonata_page_container' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_container'), 'sonata_page_breadcrumb' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_sonata_page_breadcrumb'), 'page_content' => array(object(__TwigTemplate_2aa42510ab6c10468858721df8069038), 'block_page_content')))
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite)))
     (vendor/twig/twig/src/Template.php:379)
  at Twig\Template->render(array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite)), array())
     (vendor/twig/twig/src/TemplateWrapper.php:40)
  at Twig\TemplateWrapper->render(array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite)))
     (vendor/twig/twig/src/Environment.php:277)
  at Twig\Environment->render('@SonataPage/layout.html.twig', array('error_codes' => array('_page_internal_error_not_found', '_page_internal_error_fatal'), 'page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite)))
     (vendor/sonata-project/page-bundle/src/Page/TemplateManager.php:99)
  at Sonata\PageBundle\Page\TemplateManager->renderResponse('default', array('page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite)), object(Response))
     (vendor/sonata-project/page-bundle/src/Page/Service/DefaultPageService.php:56)
  at Sonata\PageBundle\Page\Service\DefaultPageService->execute(object(SnapshotPageProxy), object(Request), array('page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite)), object(Response))
     (vendor/sonata-project/page-bundle/src/Page/PageServiceManager.php:83)
  at Sonata\PageBundle\Page\PageServiceManager->execute(object(SnapshotPageProxy), object(Request), array('page' => object(SnapshotPageProxy), 'site' => object(SonataPageSite)), object(Response))
     (vendor/symfony/http-kernel/HttpKernel.php:159)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:81)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:29)   
```

</p>
</details>

<details><summary>Breadcrumb</summary>
<p>

Related issue: https://github.com/sonata-project/SonataSeoBundle/issues/685
```
RuntimeException:
The block "sonata.page.block.breadcrumb" must implement Sonata\BlockBundle\Block\Service\EditableBlockService

  at vendor/sonata-project/page-bundle/src/Admin/BlockAdmin.php:221
  at Sonata\PageBundle\Admin\BlockAdmin->configureBlockFields(object(FormMapper), object(SonataPageBlock))
     (vendor/sonata-project/page-bundle/src/Admin/BlockAdmin.php:179)
  at Sonata\PageBundle\Admin\BlockAdmin->configureFormFields(object(FormMapper))
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:819)
  at Sonata\AdminBundle\Admin\AbstractAdmin->defineFormBuilder(object(FormBuilder))
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:799)
  at Sonata\AdminBundle\Admin\AbstractAdmin->getFormBuilder()
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:2522)
  at Sonata\AdminBundle\Admin\AbstractAdmin->buildForm()
     (vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php:871)
  at Sonata\AdminBundle\Admin\AbstractAdmin->getForm()
     (vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php:571)
  at Sonata\AdminBundle\Controller\CRUDController->createAction(object(Request))
     (vendor/sonata-project/page-bundle/src/Controller/BlockAdminController.php:102)
  at Sonata\PageBundle\Controller\BlockAdminController->createAction(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:159)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:81)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:29)                
```

</p>
</details>

<details><summary>Shared block</summary>
<p>

```
Twig\Error\RuntimeError:
An exception has been thrown during the rendering of a template ("Parameter "id" for route "admin_app_sonatapagepage_sonatapageblock_edit" must match "[^/]++" ("" given) to generate a corresponding URL.").

  at vendor/sonata-project/admin-bundle/src/Resources/views/Helper/short-object-description.html.twig:3
  at Twig\Template->displayWithErrorHandling(array('admin' => object(BlockAdmin), 'description' => 'Test A ~ #9', 'object' => object(SonataPageBlock), 'link_parameters' => array(), 'wrap_fields_with_addons' => true, 'app' => object(AppVariable), 'sonata_block' => object(GlobalVariables), 'sonata_config' => object(SonataConfiguration), 'sonata_page' => object(GlobalVariables), 'sonata_page_admin' => object(PageAdmin)), array())
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('admin' => object(BlockAdmin), 'description' => 'Test A ~ #9', 'object' => object(SonataPageBlock), 'link_parameters' => array()))
     (vendor/twig/twig/src/Template.php:379)
  at Twig\Template->render(array('admin' => object(BlockAdmin), 'description' => 'Test A ~ #9', 'object' => object(SonataPageBlock), 'link_parameters' => array()), array())
     (vendor/twig/twig/src/TemplateWrapper.php:40)
  at Twig\TemplateWrapper->render(array('admin' => object(BlockAdmin), 'description' => 'Test A ~ #9', 'object' => object(SonataPageBlock), 'link_parameters' => array()))
     (vendor/twig/twig/src/Environment.php:277)
  at Twig\Environment->render('@SonataAdmin/Helper/short-object-description.html.twig', array('admin' => object(BlockAdmin), 'description' => 'Test A ~ #9', 'object' => object(SonataPageBlock), 'link_parameters' => array()))
     (vendor/sonata-project/admin-bundle/src/Action/GetShortObjectDescriptionAction.php:84)
  at Sonata\AdminBundle\Action\GetShortObjectDescriptionAction->__invoke(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:159)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:81)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:29)  
```

</p>
</details>

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is where the bug happens.

Closes #1586

### CODE REVIEW

**Comment by eerison** [comment]
ahhh wait, will it solve the share blocks issue as well? or will you create other PR?

**Comment by jordisala1991** [comment]
> ahhh wait, will it solve the share blocks issue as well? or will you create other PR?

If it works, and we like the solution, I will apply to the other block too, yes.

**Comment by haivala** [comment]
Works!

**Comment by VincentLanglet** [comment]
> > ahhh wait, will it solve the share blocks issue as well? or will you create other PR?
> 
> If it works, and we like the solution, I will apply to the other block too, yes.

I didn't follow enough the topic in order to understand why such change is needed but I think the solution is ok. (and it works)

Can it be tested ?

File: src/Block/ChildrenPagesBlockService.php [hunk 1]
```diff
@@ -178,15 +176,30 @@ public function load(BlockInterface $block): void
...
-            }
-        }
+        $formBuilder = $form->getFormBuilder()->create('pageId', PageSelectorType::class, [
+            'model_manager' => $this->pageAdmin->getModelManager(),
+            'class' => $this->pageAdmin->getClass(),
+            'site' => null !== $page ? $page->getSite() : null,
+            'required' => false,
+            'label' => 'form.label_page',
+        ]);
+        $formBuilder->addModelTransformer(new CallbackTransformer(
```
Comment (jordisala1991) [inline src/Block/ChildrenPagesBlockService.php:194]: The problem @VincentLanglet is that when you create the field for the 'pageId', pageId is not a mapped field on any entity, and when it gets to doctrine to store the information, it gets in the form of a Page (PageInterface), doctrie does not understand that I want to store only the id (It does for mapped fields tho) and with the model transformer we solve the issue.

Previously on 3.x we had some prePersist and preUpdate hooks that essentially were doing the same transformation, this solution looks cleaner to me.

Comment (VincentLanglet) [reply src/Block/ChildrenPagesBlockService.php:194]: Seems better to have a standalone form indeed rather than a prepist/preupdate fix.

**Comment by jordisala1991** [comment]
> > > ahhh wait, will it solve the share blocks issue as well? or will you create other PR?
> > 
> > 
> > If it works, and we like the solution, I will apply to the other block too, yes.
> 
> I didn't follow enough the topic in order to understand why such change is needed but I think the solution is ok. (and it works)
> 
> Can it be tested ?

I think it should be, let me try it.

File: tests/Functional/Admin/SharedBlockAdminTest.php [hunk 2]
```diff
@@ -70,6 +70,10 @@ public function testFormsUrls(string $url, array $parameters, string $button, ar
         $client->followRedirect();
 
         self::assertResponseIsSuccessful();
+
+        $client->request('GET', '/admin/tests/app/sonatapageblock/shared/2/edit');
+
+        self::assertResponseIsSuccessful();
```
Comment (jordisala1991) [inline tests/Functional/Admin/SharedBlockAdminTest.php]:
```suggestion
```

**Comment by jordisala1991** [comment]
I think I have fixed both blocks, @haivala @eerison , can you check?

I have break the build on the first commits, and then fixed on the next 2, @VincentLanglet

File: src/Block/ChildrenPagesBlockService.php [hunk 3]
```diff
@@ -111,8 +114,9 @@ public function configureEditForm(FormMapper $form, BlockInterface $block): void
             return;
         }
 
-        $page = $block->getPage();
-        $site = null !== $page ? $page->getSite() : null;
+        if (!$form instanceof AdminFormMapper) {
+            throw new \InvalidArgumentException('Shared Block requires to be used in the Admin context');
```
Comment (jordisala1991) [inline src/Block/ChildrenPagesBlockService.php]:
```suggestion
            throw new \InvalidArgumentException('Children Pages Block requires to be used in the Admin context');
```

File: src/Block/SharedBlockBlockService.php [hunk 4]
```diff
@@ -121,13 +118,11 @@ public function getMetadata(): MetadataInterface
 
     public function load(BlockInterface $block): void
     {
-        $sharedBlock = $block->getSetting('blockId', null);
+        $blockId = $block->getSetting('blockId', null);
 
-        if (\is_int($sharedBlock)) {
-            $sharedBlock = $this->blockManager->findOneBy(['id' => $sharedBlock]);
+        if (!$blockId instanceof PageBlockInterface) {
```
Comment (VincentLanglet) [inline src/Block/SharedBlockBlockService.php:123]: This is weird having a setting blockId which is not an id but the object. Should we rename it ?

**Review by VincentLanglet — CHANGES_REQUESTED** [review]

File: src/Block/ChildrenPagesBlockService.php [hunk 5]
```diff
@@ -172,21 +170,32 @@ public function configureSettings(OptionsResolver $resolver): void
...
     {
-        if (!$block instanceof PageBlockInterface) {
-            return;
-        }
-
         $pageId = $block->getSetting('pageId', null);
 
-        if (null !== $pageId && !$pageId instanceof PageInterface) {
-            $cmsManager = $this->cmsManagerSelector->retrieve();
+        if (!$pageId instanceof PageInterface) {
```
Comment (VincentLanglet) [inline src/Block/ChildrenPagesBlockService.php:175]: Seems like it's the same here...

File: src/Block/SharedBlockBlockService.php (hunk 4 above)
Comment (jordisala1991) [reply src/Block/SharedBlockBlockService.php:123]: We can maybe rename the variable, but not the key of the array. otherwise we will break everything stored on the db of users migrating from 3 to 4.

it is called blockId because on the db is stored as id, but I agree it could been easier to simply call it block.

Comment (VincentLanglet) [reply src/Block/SharedBlockBlockService.php:123]:
```
$this->blockManager->findOneBy(['id' => $blockId])
```
can return null.
Should we throw an exception in that case ?

File: src/Block/ChildrenPagesBlockService.php (hunk 5 above)
Comment (VincentLanglet) [reply src/Block/ChildrenPagesBlockService.php:175]: $this->pageAdmin->getObject($pageId) can return null ; should we throw an exception in that case ?

File: src/Block/SharedBlockBlockService.php (hunk 4 above)
Comment (VincentLanglet) [reply src/Block/SharedBlockBlockService.php:123]: > We can maybe rename the variable, but not the key of the array. otherwise we will break everything stored on the db of users migrating from 3 to 4.
> 
> it is called blockId because on the db is stored as id, but I agree it could been easier to simply call id block.

Then we can keep it like this indeed. We might just need to handle the case where we don't find the block in database.

Comment (jordisala1991) [reply src/Block/SharedBlockBlockService.php:123]: I guess not, I think is better to leave null.

Use case:

1. create a page
2. create a block pointing to that page
3. remove the page
4. edit the block, you dont want to get an exception, block wont be automatically removed but instead it will be empty

I guess thats how it should work.

**Review by VincentLanglet — APPROVED** [review]
